// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package relaystores

import (
	"github.com/boatkit-io/restream/examples/tictactoerelay/internal/game"
	"github.com/boatkit-io/restream/pkg/restream"
)

const (
	// BoardStoreName is the restream store name for BoardStore.
	BoardStoreName = "BoardStore"
)

// NewRelayStores creates relay stores for all generated ReStream stores in this package.
func NewRelayStores() []restream.Store {
	return []restream.Store{
		restream.NewRelayStore[game.BoardStoreState, *game.BoardStoreState, *game.BoardStoreStatePartial](
			BoardStoreName,
			&game.BoardStoreState{},
			restream.AccessLevelPublic,
		),
	}
}
