// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package ffrpc

import (
	"github.com/boatkit-io/restream/pkg/binarystreams"
	"github.com/boatkit-io/restream/pkg/restream"
)

// RadioTransmitAudioRequest is a request object for the Radio.TransmitAudio FFRPC call
type RadioTransmitAudioRequest struct { //nolint:revive
	RadioID  string
	Sequence uint32
	Audio    []byte
}

// RadioTransmitAudioRequestFieldInfo is the static field info for the RadioTransmitAudioRequest struct
var RadioTransmitAudioRequestFieldInfo = []restream.FieldInfo{
	{Name: "RadioID", FieldIdx: 0, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeString}},
	{Name: "Sequence", FieldIdx: 1, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint32}},
	{Name: "Audio", FieldIdx: 2, VarInfo: &restream.VarInfoArray{NotNil: false, ElemType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint8, MappedType: restream.Ptr("byte")}}},
}

// Serialize serializes this structure to a binary writer
func (s *RadioTransmitAudioRequest) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	if err := restream.SerializeValue(s.RadioID, w, RadioTransmitAudioRequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := restream.SerializeValue(s.Sequence, w, RadioTransmitAudioRequestFieldInfo[1].VarInfo); err != nil {
		return err
	}
	if err := restream.SerializeValue(s.Audio, w, RadioTransmitAudioRequestFieldInfo[2].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *RadioTransmitAudioRequest) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	if err := restream.DeserializeValue(&s.RadioID, r, RadioTransmitAudioRequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := restream.DeserializeValue(&s.Sequence, r, RadioTransmitAudioRequestFieldInfo[1].VarInfo); err != nil {
		return err
	}
	if err := restream.DeserializeValue(&s.Audio, r, RadioTransmitAudioRequestFieldInfo[2].VarInfo); err != nil {
		return err
	}
	return nil
}
