// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package game

import (
	"time"

	"github.com/boatkit-io/restream/pkg/binarystreams"
	"github.com/boatkit-io/restream/pkg/restream"
)

// ServerTimeEvent is an event packet object for the ServerTime event
type ServerTimeEvent struct { //nolint:revive
	CurrentTime time.Time
}

// ServerTimeEventFieldInfo is the static field info for the ServerTimeEvent struct
var ServerTimeEventFieldInfo = []restream.FieldInfo{
	{Name: "CurrentTime", FieldIdx: 0, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeTime}},
}

// Serialize serializes this structure to a binary writer
func (s *ServerTimeEvent) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	if err := restream.SerializeValue(s.CurrentTime, w, ServerTimeEventFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *ServerTimeEvent) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	if err := restream.DeserializeValue(&s.CurrentTime, r, ServerTimeEventFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}
