// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package game

import (
	"github.com/boatkit-io/restream/pkg/restream"
)

// NewRelayStores creates relay stores for all generated ReStream stores in this package.
func NewRelayStores() []restream.Store {
	return []restream.Store{
		restream.NewRelayStore[BoardStoreState, *BoardStoreState, *BoardStoreStatePartial](
			BoardStoreName,
			&BoardStoreState{},
			restream.AccessLevelPublic,
		),
	}
}
