// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package storetest

import (
	"github.com/boatkit-io/restream/pkg/binarystreams"
	"github.com/boatkit-io/restream/pkg/restream"
)

// TestAFieldInfo is the static field info for the TestA struct
var TestAFieldInfo = []restream.FieldInfo{
	{Name: "A", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoStruct{Name: "TestB", Package: "storetest"}},
	{Name: "B", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoStruct{Name: "TestB", Package: "storetest"}},
}

// TestAFieldMap is the static field map for the TestA struct
var TestAFieldMap = map[byte]*restream.FieldInfo{
	1: &TestAFieldInfo[0],
	2: &TestAFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestA) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(&s.A, &TestAFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(&s.B, &TestAFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestA) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.A,
		&s.B,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestAFieldInfo, TestAFieldMap, fieldPtrs)
}

// TestAPartial is a partial struct for TestA
type TestAPartial struct {
	A *restream.PartialValue[TestB, *TestBPartial]
	B *restream.PartialValue[TestB, *TestBPartial]
}

// MergeOntoPartial merges this partial onto another partial
func (s *TestAPartial) MergeOntoPartial(por any) {
	po := por.(*TestAPartial)
	if s.A != nil {
		if po.A == nil {
			po.A = s.A
		} else {
			s.A.MergeOntoPartial(po.A)
		}
	}
	if s.B != nil {
		if po.B == nil {
			po.B = s.B
		} else {
			s.B.MergeOntoPartial(po.B)
		}
	}
}

// ApplyTo applies this partial to the full version of the struct
func (s *TestAPartial) ApplyTo(por any) [][]any {
	po, ok := por.(*TestA)
	if !ok {
		pop := por.(**TestA)
		if *pop == nil {
			*pop = &TestA{}
		}
		po = *pop
	}
	ret := [][]any{}
	if s.A != nil {
		fs := s.A.ApplyTo(&po.A)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "A"), f...))
		}
	}
	if s.B != nil {
		fs := s.B.ApplyTo(&po.B)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "B"), f...))
		}
	}
	return restream.ReduceFieldPaths(ret)
}

// FilterToFields returns a new partial containing only changes matching the requested field paths
func (s *TestAPartial) FilterToFields(fields [][]any) (restream.Partial, bool) {
	ret := &TestAPartial{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return s, true
		}
	}
	if s.A != nil {
		childFields := restream.ChildFieldsForField(fields, "A")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.A, childFields)
			if ok {
				ret.A = filtered
				included = true
			}
		}
	}
	if s.B != nil {
		childFields := restream.ChildFieldsForField(fields, "B")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.B, childFields)
			if ok {
				ret.B = filtered
				included = true
			}
		}
	}
	return ret, included
}

// PartialForFields returns a snapshot partial containing the requested field paths
func (s *TestA) PartialForFields(fields [][]any) (restream.Partial, bool) {
	fields = restream.ReduceFieldPaths(fields)
	ret := &TestAPartial{}
	included := false
	if partial, ok := s.partialForFieldsA(restream.ChildFieldsForField(fields, "A")); ok {
		ret.A = partial
		included = true
	}
	if partial, ok := s.partialForFieldsB(restream.ChildFieldsForField(fields, "B")); ok {
		ret.B = partial
		included = true
	}
	return ret, included
}

func (s *TestA) partialForFieldsA(fields [][]any) (*restream.PartialValue[TestB, *TestBPartial], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := &restream.PartialValue[TestB, *TestBPartial]{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(restream.Ptr(s.A)), true
		}
		partial, ok := (&s.A).PartialForFields([][]any{field})
		if ok {
			ret.ApplyPartial(partial.(*TestBPartial))
			included = true
		}
	}
	return ret, included
}

func (s *TestA) partialForFieldsB(fields [][]any) (*restream.PartialValue[TestB, *TestBPartial], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := &restream.PartialValue[TestB, *TestBPartial]{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(restream.Ptr(s.B)), true
		}
		partial, ok := (&s.B).PartialForFields([][]any{field})
		if ok {
			ret.ApplyPartial(partial.(*TestBPartial))
			included = true
		}
	}
	return ret, included
}

// TestAPartialFieldInfo is the static field info for the TestAPartial struct
var TestAPartialFieldInfo = []restream.FieldInfo{
	{Name: "A", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialValue", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoStruct{Name: "TestB", Package: "storetest"}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestBPartial", Package: "storetest"}}}}}},
	{Name: "B", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialValue", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoStruct{Name: "TestB", Package: "storetest"}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestBPartial", Package: "storetest"}}}}}},
}

// TestAPartialFieldMap is the static field map for the TestAPartial struct
var TestAPartialFieldMap = map[byte]*restream.FieldInfo{
	1: &TestAPartialFieldInfo[0],
	2: &TestAPartialFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestAPartial) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.A, &TestAPartialFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.B, &TestAPartialFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestAPartial) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.A,
		&s.B,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestAPartialFieldInfo, TestAPartialFieldMap, fieldPtrs)
}

// TestArrayStateFieldInfo is the static field info for the TestArrayState struct
var TestArrayStateFieldInfo = []restream.FieldInfo{
	{Name: "Numbers", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoArray{NotNil: false, ElemType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint64, MappedType: restream.Ptr("uint")}}},
	{Name: "Items", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoArray{NotNil: false, ElemType: &restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}}},
	{Name: "PtrItems", FieldIdx: 2, FieldID: 3, VarInfo: &restream.VarInfoArray{NotNil: false, ElemType: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}}}},
}

// TestArrayStateFieldMap is the static field map for the TestArrayState struct
var TestArrayStateFieldMap = map[byte]*restream.FieldInfo{
	1: &TestArrayStateFieldInfo[0],
	2: &TestArrayStateFieldInfo[1],
	3: &TestArrayStateFieldInfo[2],
}

// Serialize serializes this structure to a binary writer
func (s *TestArrayState) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.Numbers, &TestArrayStateFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.Items, &TestArrayStateFieldInfo[1], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.PtrItems, &TestArrayStateFieldInfo[2], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestArrayState) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.Numbers,
		&s.Items,
		&s.PtrItems,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestArrayStateFieldInfo, TestArrayStateFieldMap, fieldPtrs)
}

// TestArrayStatePartial is a partial struct for TestArrayState
type TestArrayStatePartial struct {
	Numbers  *restream.PartialArray[uint]
	Items    *restream.PartialModArray[TestMapData, *TestMapDataPartial]
	PtrItems *restream.PartialModArray[*TestMapData, *TestMapDataPartial]
}

// MergeOntoPartial merges this partial onto another partial
func (s *TestArrayStatePartial) MergeOntoPartial(por any) {
	po := por.(*TestArrayStatePartial)
	if s.Numbers != nil {
		if po.Numbers == nil {
			po.Numbers = s.Numbers
		} else {
			s.Numbers.MergeOntoPartial(po.Numbers)
		}
	}
	if s.Items != nil {
		if po.Items == nil {
			po.Items = s.Items
		} else {
			s.Items.MergeOntoPartial(po.Items)
		}
	}
	if s.PtrItems != nil {
		if po.PtrItems == nil {
			po.PtrItems = s.PtrItems
		} else {
			s.PtrItems.MergeOntoPartial(po.PtrItems)
		}
	}
}

// ApplyTo applies this partial to the full version of the struct
func (s *TestArrayStatePartial) ApplyTo(por any) [][]any {
	po, ok := por.(*TestArrayState)
	if !ok {
		pop := por.(**TestArrayState)
		if *pop == nil {
			*pop = &TestArrayState{}
		}
		po = *pop
	}
	ret := [][]any{}
	if s.Numbers != nil {
		fs := s.Numbers.ApplyTo(&po.Numbers)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "Numbers"), f...))
		}
	}
	if s.Items != nil {
		fs := s.Items.ApplyTo(&po.Items)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "Items"), f...))
		}
	}
	if s.PtrItems != nil {
		fs := s.PtrItems.ApplyTo(&po.PtrItems)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "PtrItems"), f...))
		}
	}
	return restream.ReduceFieldPaths(ret)
}

// FilterToFields returns a new partial containing only changes matching the requested field paths
func (s *TestArrayStatePartial) FilterToFields(fields [][]any) (restream.Partial, bool) {
	ret := &TestArrayStatePartial{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return s, true
		}
	}
	if s.Numbers != nil {
		childFields := restream.ChildFieldsForField(fields, "Numbers")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.Numbers, childFields)
			if ok {
				ret.Numbers = filtered
				included = true
			}
		}
	}
	if s.Items != nil {
		childFields := restream.ChildFieldsForField(fields, "Items")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.Items, childFields)
			if ok {
				ret.Items = filtered
				included = true
			}
		}
	}
	if s.PtrItems != nil {
		childFields := restream.ChildFieldsForField(fields, "PtrItems")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.PtrItems, childFields)
			if ok {
				ret.PtrItems = filtered
				included = true
			}
		}
	}
	return ret, included
}

// PartialForFields returns a snapshot partial containing the requested field paths
func (s *TestArrayState) PartialForFields(fields [][]any) (restream.Partial, bool) {
	fields = restream.ReduceFieldPaths(fields)
	ret := &TestArrayStatePartial{}
	included := false
	if partial, ok := s.partialForFieldsNumbers(restream.ChildFieldsForField(fields, "Numbers")); ok {
		ret.Numbers = partial
		included = true
	}
	if partial, ok := s.partialForFieldsItems(restream.ChildFieldsForField(fields, "Items")); ok {
		ret.Items = partial
		included = true
	}
	if partial, ok := s.partialForFieldsPtrItems(restream.ChildFieldsForField(fields, "PtrItems")); ok {
		ret.PtrItems = partial
		included = true
	}
	return ret, included
}

func (s *TestArrayState) partialForFieldsNumbers(fields [][]any) (*restream.PartialArray[uint], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := restream.NewPartialArray[uint]()
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(s.Numbers), true
		}
		index, ok := restream.FieldPathPartToIndex(field[0])
		if !ok || index < 0 || index >= len(s.Numbers) {
			continue
		}
		value := s.Numbers[index]
		ret.Set(index, value)
		included = true
	}
	return ret, included
}

func (s *TestArrayState) partialForFieldsItems(fields [][]any) (*restream.PartialModArray[TestMapData, *TestMapDataPartial], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := restream.NewPartialModArray[TestMapData, *TestMapDataPartial]()
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(s.Items), true
		}
		index, ok := restream.FieldPathPartToIndex(field[0])
		if !ok || index < 0 || index >= len(s.Items) {
			continue
		}
		value := s.Items[index]
		if len(field) == 1 {
			ret.Set(index, value)
			included = true
			continue
		}
		partial, ok := (&value).PartialForFields([][]any{field[1:]})
		if ok {
			ret.ApplyPartial(index, partial.(*TestMapDataPartial))
			included = true
		}
	}
	return ret, included
}

func (s *TestArrayState) partialForFieldsPtrItems(fields [][]any) (*restream.PartialModArray[*TestMapData, *TestMapDataPartial], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := restream.NewPartialModArray[*TestMapData, *TestMapDataPartial]()
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(s.PtrItems), true
		}
		index, ok := restream.FieldPathPartToIndex(field[0])
		if !ok || index < 0 || index >= len(s.PtrItems) {
			continue
		}
		value := s.PtrItems[index]
		if len(field) == 1 {
			ret.Set(index, value)
			included = true
			continue
		}
		if value == nil {
			ret.Set(index, value)
			included = true
			continue
		}
		partial, ok := value.PartialForFields([][]any{field[1:]})
		if ok {
			ret.ApplyPartial(index, partial.(*TestMapDataPartial))
			included = true
		}
	}
	return ret, included
}

// TestArrayStatePartialFieldInfo is the static field info for the TestArrayStatePartial struct
var TestArrayStatePartialFieldInfo = []restream.FieldInfo{
	{Name: "Numbers", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialArray", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint64, MappedType: restream.Ptr("uint")}}}}},
	{Name: "Items", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialModArray", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapDataPartial", Package: "storetest"}}}}}},
	{Name: "PtrItems", FieldIdx: 2, FieldID: 3, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialModArray", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapDataPartial", Package: "storetest"}}}}}},
}

// TestArrayStatePartialFieldMap is the static field map for the TestArrayStatePartial struct
var TestArrayStatePartialFieldMap = map[byte]*restream.FieldInfo{
	1: &TestArrayStatePartialFieldInfo[0],
	2: &TestArrayStatePartialFieldInfo[1],
	3: &TestArrayStatePartialFieldInfo[2],
}

// Serialize serializes this structure to a binary writer
func (s *TestArrayStatePartial) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.Numbers, &TestArrayStatePartialFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.Items, &TestArrayStatePartialFieldInfo[1], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.PtrItems, &TestArrayStatePartialFieldInfo[2], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestArrayStatePartial) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.Numbers,
		&s.Items,
		&s.PtrItems,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestArrayStatePartialFieldInfo, TestArrayStatePartialFieldMap, fieldPtrs)
}

// TestBFieldInfo is the static field info for the TestB struct
var TestBFieldInfo = []restream.FieldInfo{
	{Name: "A", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoStruct{Name: "TestC", Package: "storetest"}},
	{Name: "B", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoStruct{Name: "TestC", Package: "storetest"}},
}

// TestBFieldMap is the static field map for the TestB struct
var TestBFieldMap = map[byte]*restream.FieldInfo{
	1: &TestBFieldInfo[0],
	2: &TestBFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestB) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(&s.A, &TestBFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(&s.B, &TestBFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestB) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.A,
		&s.B,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestBFieldInfo, TestBFieldMap, fieldPtrs)
}

// TestBPartial is a partial struct for TestB
type TestBPartial struct {
	A *restream.PartialValue[TestC, *TestCPartial]
	B *restream.PartialValue[TestC, *TestCPartial]
}

// MergeOntoPartial merges this partial onto another partial
func (s *TestBPartial) MergeOntoPartial(por any) {
	po := por.(*TestBPartial)
	if s.A != nil {
		if po.A == nil {
			po.A = s.A
		} else {
			s.A.MergeOntoPartial(po.A)
		}
	}
	if s.B != nil {
		if po.B == nil {
			po.B = s.B
		} else {
			s.B.MergeOntoPartial(po.B)
		}
	}
}

// ApplyTo applies this partial to the full version of the struct
func (s *TestBPartial) ApplyTo(por any) [][]any {
	po, ok := por.(*TestB)
	if !ok {
		pop := por.(**TestB)
		if *pop == nil {
			*pop = &TestB{}
		}
		po = *pop
	}
	ret := [][]any{}
	if s.A != nil {
		fs := s.A.ApplyTo(&po.A)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "A"), f...))
		}
	}
	if s.B != nil {
		fs := s.B.ApplyTo(&po.B)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "B"), f...))
		}
	}
	return restream.ReduceFieldPaths(ret)
}

// FilterToFields returns a new partial containing only changes matching the requested field paths
func (s *TestBPartial) FilterToFields(fields [][]any) (restream.Partial, bool) {
	ret := &TestBPartial{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return s, true
		}
	}
	if s.A != nil {
		childFields := restream.ChildFieldsForField(fields, "A")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.A, childFields)
			if ok {
				ret.A = filtered
				included = true
			}
		}
	}
	if s.B != nil {
		childFields := restream.ChildFieldsForField(fields, "B")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.B, childFields)
			if ok {
				ret.B = filtered
				included = true
			}
		}
	}
	return ret, included
}

// PartialForFields returns a snapshot partial containing the requested field paths
func (s *TestB) PartialForFields(fields [][]any) (restream.Partial, bool) {
	fields = restream.ReduceFieldPaths(fields)
	ret := &TestBPartial{}
	included := false
	if partial, ok := s.partialForFieldsA(restream.ChildFieldsForField(fields, "A")); ok {
		ret.A = partial
		included = true
	}
	if partial, ok := s.partialForFieldsB(restream.ChildFieldsForField(fields, "B")); ok {
		ret.B = partial
		included = true
	}
	return ret, included
}

func (s *TestB) partialForFieldsA(fields [][]any) (*restream.PartialValue[TestC, *TestCPartial], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := &restream.PartialValue[TestC, *TestCPartial]{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(restream.Ptr(s.A)), true
		}
		partial, ok := (&s.A).PartialForFields([][]any{field})
		if ok {
			ret.ApplyPartial(partial.(*TestCPartial))
			included = true
		}
	}
	return ret, included
}

func (s *TestB) partialForFieldsB(fields [][]any) (*restream.PartialValue[TestC, *TestCPartial], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := &restream.PartialValue[TestC, *TestCPartial]{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(restream.Ptr(s.B)), true
		}
		partial, ok := (&s.B).PartialForFields([][]any{field})
		if ok {
			ret.ApplyPartial(partial.(*TestCPartial))
			included = true
		}
	}
	return ret, included
}

// TestBPartialFieldInfo is the static field info for the TestBPartial struct
var TestBPartialFieldInfo = []restream.FieldInfo{
	{Name: "A", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialValue", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoStruct{Name: "TestC", Package: "storetest"}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestCPartial", Package: "storetest"}}}}}},
	{Name: "B", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialValue", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoStruct{Name: "TestC", Package: "storetest"}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestCPartial", Package: "storetest"}}}}}},
}

// TestBPartialFieldMap is the static field map for the TestBPartial struct
var TestBPartialFieldMap = map[byte]*restream.FieldInfo{
	1: &TestBPartialFieldInfo[0],
	2: &TestBPartialFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestBPartial) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.A, &TestBPartialFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.B, &TestBPartialFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestBPartial) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.A,
		&s.B,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestBPartialFieldInfo, TestBPartialFieldMap, fieldPtrs)
}

// TestCFieldInfo is the static field info for the TestC struct
var TestCFieldInfo = []restream.FieldInfo{
	{Name: "A", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeInt64, MappedType: restream.Ptr("int")}},
	{Name: "B", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeInt64, MappedType: restream.Ptr("int")}},
}

// TestCFieldMap is the static field map for the TestC struct
var TestCFieldMap = map[byte]*restream.FieldInfo{
	1: &TestCFieldInfo[0],
	2: &TestCFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestC) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.A, &TestCFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.B, &TestCFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestC) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.A,
		&s.B,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestCFieldInfo, TestCFieldMap, fieldPtrs)
}

// TestCPartial is a partial struct for TestC
type TestCPartial struct {
	A *int
	B *int
}

// MergeOntoPartial merges this partial onto another partial
func (s *TestCPartial) MergeOntoPartial(por any) {
	po := por.(*TestCPartial)
	if s.A != nil {
		po.A = s.A
	}
	if s.B != nil {
		po.B = s.B
	}
}

// ApplyTo applies this partial to the full version of the struct
func (s *TestCPartial) ApplyTo(por any) [][]any {
	po, ok := por.(*TestC)
	if !ok {
		pop := por.(**TestC)
		if *pop == nil {
			*pop = &TestC{}
		}
		po = *pop
	}
	ret := [][]any{}
	if s.A != nil {
		po.A = *s.A
		ret = append(ret, []any{"A"})
	}
	if s.B != nil {
		po.B = *s.B
		ret = append(ret, []any{"B"})
	}
	return restream.ReduceFieldPaths(ret)
}

// FilterToFields returns a new partial containing only changes matching the requested field paths
func (s *TestCPartial) FilterToFields(fields [][]any) (restream.Partial, bool) {
	ret := &TestCPartial{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return s, true
		}
	}
	if s.A != nil {
		childFields := restream.ChildFieldsForField(fields, "A")
		if len(childFields) > 0 {
			ret.A = s.A
			included = true
		}
	}
	if s.B != nil {
		childFields := restream.ChildFieldsForField(fields, "B")
		if len(childFields) > 0 {
			ret.B = s.B
			included = true
		}
	}
	return ret, included
}

// PartialForFields returns a snapshot partial containing the requested field paths
func (s *TestC) PartialForFields(fields [][]any) (restream.Partial, bool) {
	fields = restream.ReduceFieldPaths(fields)
	ret := &TestCPartial{}
	included := false
	if partial, ok := s.partialForFieldsA(restream.ChildFieldsForField(fields, "A")); ok {
		ret.A = partial
		included = true
	}
	if partial, ok := s.partialForFieldsB(restream.ChildFieldsForField(fields, "B")); ok {
		ret.B = partial
		included = true
	}
	return ret, included
}

func (s *TestC) partialForFieldsA(fields [][]any) (*int, bool) {
	if len(fields) == 0 {
		return nil, false
	}
	for _, field := range fields {
		if len(field) == 0 {
			return restream.Ptr(s.A), true
		}
	}
	return nil, false
}

func (s *TestC) partialForFieldsB(fields [][]any) (*int, bool) {
	if len(fields) == 0 {
		return nil, false
	}
	for _, field := range fields {
		if len(field) == 0 {
			return restream.Ptr(s.B), true
		}
	}
	return nil, false
}

// TestCPartialFieldInfo is the static field info for the TestCPartial struct
var TestCPartialFieldInfo = []restream.FieldInfo{
	{Name: "A", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeInt64, MappedType: restream.Ptr("int")}}},
	{Name: "B", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeInt64, MappedType: restream.Ptr("int")}}},
}

// TestCPartialFieldMap is the static field map for the TestCPartial struct
var TestCPartialFieldMap = map[byte]*restream.FieldInfo{
	1: &TestCPartialFieldInfo[0],
	2: &TestCPartialFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestCPartial) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.A, &TestCPartialFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.B, &TestCPartialFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestCPartial) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.A,
		&s.B,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestCPartialFieldInfo, TestCPartialFieldMap, fieldPtrs)
}

// TestMapDataFieldInfo is the static field info for the TestMapData struct
var TestMapDataFieldInfo = []restream.FieldInfo{
	{Name: "Number", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint64, MappedType: restream.Ptr("uint")}},
	{Name: "Data", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoArray{NotNil: false, ElemType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint8, MappedType: restream.Ptr("byte")}}},
}

// TestMapDataFieldMap is the static field map for the TestMapData struct
var TestMapDataFieldMap = map[byte]*restream.FieldInfo{
	1: &TestMapDataFieldInfo[0],
	2: &TestMapDataFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestMapData) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.Number, &TestMapDataFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.Data, &TestMapDataFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestMapData) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.Number,
		&s.Data,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestMapDataFieldInfo, TestMapDataFieldMap, fieldPtrs)
}

// TestMapDataPartial is a partial struct for TestMapData
type TestMapDataPartial struct {
	Number *uint
	Data   *restream.PartialArray[byte]
}

// MergeOntoPartial merges this partial onto another partial
func (s *TestMapDataPartial) MergeOntoPartial(por any) {
	po := por.(*TestMapDataPartial)
	if s.Number != nil {
		po.Number = s.Number
	}
	if s.Data != nil {
		if po.Data == nil {
			po.Data = s.Data
		} else {
			s.Data.MergeOntoPartial(po.Data)
		}
	}
}

// ApplyTo applies this partial to the full version of the struct
func (s *TestMapDataPartial) ApplyTo(por any) [][]any {
	po, ok := por.(*TestMapData)
	if !ok {
		pop := por.(**TestMapData)
		if *pop == nil {
			*pop = &TestMapData{}
		}
		po = *pop
	}
	ret := [][]any{}
	if s.Number != nil {
		po.Number = *s.Number
		ret = append(ret, []any{"Number"})
	}
	if s.Data != nil {
		fs := s.Data.ApplyTo(&po.Data)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "Data"), f...))
		}
	}
	return restream.ReduceFieldPaths(ret)
}

// FilterToFields returns a new partial containing only changes matching the requested field paths
func (s *TestMapDataPartial) FilterToFields(fields [][]any) (restream.Partial, bool) {
	ret := &TestMapDataPartial{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return s, true
		}
	}
	if s.Number != nil {
		childFields := restream.ChildFieldsForField(fields, "Number")
		if len(childFields) > 0 {
			ret.Number = s.Number
			included = true
		}
	}
	if s.Data != nil {
		childFields := restream.ChildFieldsForField(fields, "Data")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.Data, childFields)
			if ok {
				ret.Data = filtered
				included = true
			}
		}
	}
	return ret, included
}

// PartialForFields returns a snapshot partial containing the requested field paths
func (s *TestMapData) PartialForFields(fields [][]any) (restream.Partial, bool) {
	fields = restream.ReduceFieldPaths(fields)
	ret := &TestMapDataPartial{}
	included := false
	if partial, ok := s.partialForFieldsNumber(restream.ChildFieldsForField(fields, "Number")); ok {
		ret.Number = partial
		included = true
	}
	if partial, ok := s.partialForFieldsData(restream.ChildFieldsForField(fields, "Data")); ok {
		ret.Data = partial
		included = true
	}
	return ret, included
}

func (s *TestMapData) partialForFieldsNumber(fields [][]any) (*uint, bool) {
	if len(fields) == 0 {
		return nil, false
	}
	for _, field := range fields {
		if len(field) == 0 {
			return restream.Ptr(s.Number), true
		}
	}
	return nil, false
}

func (s *TestMapData) partialForFieldsData(fields [][]any) (*restream.PartialArray[byte], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := restream.NewPartialArray[byte]()
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(s.Data), true
		}
		index, ok := restream.FieldPathPartToIndex(field[0])
		if !ok || index < 0 || index >= len(s.Data) {
			continue
		}
		value := s.Data[index]
		ret.Set(index, value)
		included = true
	}
	return ret, included
}

// TestMapDataPartialFieldInfo is the static field info for the TestMapDataPartial struct
var TestMapDataPartialFieldInfo = []restream.FieldInfo{
	{Name: "Number", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint64, MappedType: restream.Ptr("uint")}}},
	{Name: "Data", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialArray", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint8, MappedType: restream.Ptr("byte")}}}}},
}

// TestMapDataPartialFieldMap is the static field map for the TestMapDataPartial struct
var TestMapDataPartialFieldMap = map[byte]*restream.FieldInfo{
	1: &TestMapDataPartialFieldInfo[0],
	2: &TestMapDataPartialFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestMapDataPartial) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.Number, &TestMapDataPartialFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.Data, &TestMapDataPartialFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestMapDataPartial) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.Number,
		&s.Data,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestMapDataPartialFieldInfo, TestMapDataPartialFieldMap, fieldPtrs)
}

// TestPrimitiveOptionalStateFieldInfo is the static field info for the TestPrimitiveOptionalState struct
var TestPrimitiveOptionalStateFieldInfo = []restream.FieldInfo{
	{Name: "Primitive", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint32}},
	{Name: "Optional", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint32}}},
}

// TestPrimitiveOptionalStateFieldMap is the static field map for the TestPrimitiveOptionalState struct
var TestPrimitiveOptionalStateFieldMap = map[byte]*restream.FieldInfo{
	1: &TestPrimitiveOptionalStateFieldInfo[0],
	2: &TestPrimitiveOptionalStateFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestPrimitiveOptionalState) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.Primitive, &TestPrimitiveOptionalStateFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.Optional, &TestPrimitiveOptionalStateFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestPrimitiveOptionalState) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.Primitive,
		&s.Optional,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestPrimitiveOptionalStateFieldInfo, TestPrimitiveOptionalStateFieldMap, fieldPtrs)
}

// TestPrimitiveOptionalStatePartial is a partial struct for TestPrimitiveOptionalState
type TestPrimitiveOptionalStatePartial struct {
	Primitive *uint32
	Optional  **uint32
}

// MergeOntoPartial merges this partial onto another partial
func (s *TestPrimitiveOptionalStatePartial) MergeOntoPartial(por any) {
	po := por.(*TestPrimitiveOptionalStatePartial)
	if s.Primitive != nil {
		po.Primitive = s.Primitive
	}
	if s.Optional != nil {
		po.Optional = s.Optional
	}
}

// ApplyTo applies this partial to the full version of the struct
func (s *TestPrimitiveOptionalStatePartial) ApplyTo(por any) [][]any {
	po, ok := por.(*TestPrimitiveOptionalState)
	if !ok {
		pop := por.(**TestPrimitiveOptionalState)
		if *pop == nil {
			*pop = &TestPrimitiveOptionalState{}
		}
		po = *pop
	}
	ret := [][]any{}
	if s.Primitive != nil {
		po.Primitive = *s.Primitive
		ret = append(ret, []any{"Primitive"})
	}
	if s.Optional != nil {
		po.Optional = *s.Optional
		ret = append(ret, []any{"Optional"})
	}
	return restream.ReduceFieldPaths(ret)
}

// FilterToFields returns a new partial containing only changes matching the requested field paths
func (s *TestPrimitiveOptionalStatePartial) FilterToFields(fields [][]any) (restream.Partial, bool) {
	ret := &TestPrimitiveOptionalStatePartial{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return s, true
		}
	}
	if s.Primitive != nil {
		childFields := restream.ChildFieldsForField(fields, "Primitive")
		if len(childFields) > 0 {
			ret.Primitive = s.Primitive
			included = true
		}
	}
	if s.Optional != nil {
		childFields := restream.ChildFieldsForField(fields, "Optional")
		if len(childFields) > 0 {
			ret.Optional = s.Optional
			included = true
		}
	}
	return ret, included
}

// PartialForFields returns a snapshot partial containing the requested field paths
func (s *TestPrimitiveOptionalState) PartialForFields(fields [][]any) (restream.Partial, bool) {
	fields = restream.ReduceFieldPaths(fields)
	ret := &TestPrimitiveOptionalStatePartial{}
	included := false
	if partial, ok := s.partialForFieldsPrimitive(restream.ChildFieldsForField(fields, "Primitive")); ok {
		ret.Primitive = partial
		included = true
	}
	if partial, ok := s.partialForFieldsOptional(restream.ChildFieldsForField(fields, "Optional")); ok {
		ret.Optional = partial
		included = true
	}
	return ret, included
}

func (s *TestPrimitiveOptionalState) partialForFieldsPrimitive(fields [][]any) (*uint32, bool) {
	if len(fields) == 0 {
		return nil, false
	}
	for _, field := range fields {
		if len(field) == 0 {
			return restream.Ptr(s.Primitive), true
		}
	}
	return nil, false
}

func (s *TestPrimitiveOptionalState) partialForFieldsOptional(fields [][]any) (**uint32, bool) {
	if len(fields) == 0 {
		return nil, false
	}
	for _, field := range fields {
		if len(field) == 0 {
			return restream.Ptr(s.Optional), true
		}
	}
	return nil, false
}

// TestPrimitiveOptionalStatePartialFieldInfo is the static field info for the TestPrimitiveOptionalStatePartial struct
var TestPrimitiveOptionalStatePartialFieldInfo = []restream.FieldInfo{
	{Name: "Primitive", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint32}}},
	{Name: "Optional", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint32}}}},
}

// TestPrimitiveOptionalStatePartialFieldMap is the static field map for the TestPrimitiveOptionalStatePartial struct
var TestPrimitiveOptionalStatePartialFieldMap = map[byte]*restream.FieldInfo{
	1: &TestPrimitiveOptionalStatePartialFieldInfo[0],
	2: &TestPrimitiveOptionalStatePartialFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *TestPrimitiveOptionalStatePartial) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.Primitive, &TestPrimitiveOptionalStatePartialFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.Optional, &TestPrimitiveOptionalStatePartialFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestPrimitiveOptionalStatePartial) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.Primitive,
		&s.Optional,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestPrimitiveOptionalStatePartialFieldInfo, TestPrimitiveOptionalStatePartialFieldMap, fieldPtrs)
}

// TestStateFieldInfo is the static field info for the TestState struct
var TestStateFieldInfo = []restream.FieldInfo{
	{Name: "MapPtrTest", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoMap{NotNil: false, KeyType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint8}, ElemType: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}}}},
	{Name: "BaseField", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeString}},
	{Name: "BaseStruct", FieldIdx: 2, FieldID: 3, VarInfo: &restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}},
	{Name: "BaseStructPtr", FieldIdx: 3, FieldID: 4, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}}},
}

// TestStateFieldMap is the static field map for the TestState struct
var TestStateFieldMap = map[byte]*restream.FieldInfo{
	1: &TestStateFieldInfo[0],
	2: &TestStateFieldInfo[1],
	3: &TestStateFieldInfo[2],
	4: &TestStateFieldInfo[3],
}

// Serialize serializes this structure to a binary writer
func (s *TestState) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.MapPtrTest, &TestStateFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.BaseField, &TestStateFieldInfo[1], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(&s.BaseStruct, &TestStateFieldInfo[2], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.BaseStructPtr, &TestStateFieldInfo[3], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestState) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.MapPtrTest,
		&s.BaseField,
		&s.BaseStruct,
		&s.BaseStructPtr,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestStateFieldInfo, TestStateFieldMap, fieldPtrs)
}

// TestStatePartial is a partial struct for TestState
type TestStatePartial struct {
	MapPtrTest    *restream.PartialModMap[uint8, *TestMapData, *TestMapDataPartial]
	BaseField     *string
	BaseStruct    *restream.PartialValue[TestMapData, *TestMapDataPartial]
	BaseStructPtr *restream.PartialValue[*TestMapData, *TestMapDataPartial]
}

// MergeOntoPartial merges this partial onto another partial
func (s *TestStatePartial) MergeOntoPartial(por any) {
	po := por.(*TestStatePartial)
	if s.MapPtrTest != nil {
		if po.MapPtrTest == nil {
			po.MapPtrTest = s.MapPtrTest
		} else {
			s.MapPtrTest.MergeOntoPartial(po.MapPtrTest)
		}
	}
	if s.BaseField != nil {
		po.BaseField = s.BaseField
	}
	if s.BaseStruct != nil {
		if po.BaseStruct == nil {
			po.BaseStruct = s.BaseStruct
		} else {
			s.BaseStruct.MergeOntoPartial(po.BaseStruct)
		}
	}
	if s.BaseStructPtr != nil {
		if po.BaseStructPtr == nil {
			po.BaseStructPtr = s.BaseStructPtr
		} else {
			s.BaseStructPtr.MergeOntoPartial(po.BaseStructPtr)
		}
	}
}

// ApplyTo applies this partial to the full version of the struct
func (s *TestStatePartial) ApplyTo(por any) [][]any {
	po, ok := por.(*TestState)
	if !ok {
		pop := por.(**TestState)
		if *pop == nil {
			*pop = &TestState{}
		}
		po = *pop
	}
	ret := [][]any{}
	if s.MapPtrTest != nil {
		fs := s.MapPtrTest.ApplyTo(&po.MapPtrTest)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "MapPtrTest"), f...))
		}
	}
	if s.BaseField != nil {
		po.BaseField = *s.BaseField
		ret = append(ret, []any{"BaseField"})
	}
	if s.BaseStruct != nil {
		fs := s.BaseStruct.ApplyTo(&po.BaseStruct)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "BaseStruct"), f...))
		}
	}
	if s.BaseStructPtr != nil {
		fs := s.BaseStructPtr.ApplyTo(&po.BaseStructPtr)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "BaseStructPtr"), f...))
		}
	}
	return restream.ReduceFieldPaths(ret)
}

// FilterToFields returns a new partial containing only changes matching the requested field paths
func (s *TestStatePartial) FilterToFields(fields [][]any) (restream.Partial, bool) {
	ret := &TestStatePartial{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return s, true
		}
	}
	if s.MapPtrTest != nil {
		childFields := restream.ChildFieldsForField(fields, "MapPtrTest")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.MapPtrTest, childFields)
			if ok {
				ret.MapPtrTest = filtered
				included = true
			}
		}
	}
	if s.BaseField != nil {
		childFields := restream.ChildFieldsForField(fields, "BaseField")
		if len(childFields) > 0 {
			ret.BaseField = s.BaseField
			included = true
		}
	}
	if s.BaseStruct != nil {
		childFields := restream.ChildFieldsForField(fields, "BaseStruct")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.BaseStruct, childFields)
			if ok {
				ret.BaseStruct = filtered
				included = true
			}
		}
	}
	if s.BaseStructPtr != nil {
		childFields := restream.ChildFieldsForField(fields, "BaseStructPtr")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.BaseStructPtr, childFields)
			if ok {
				ret.BaseStructPtr = filtered
				included = true
			}
		}
	}
	return ret, included
}

// PartialForFields returns a snapshot partial containing the requested field paths
func (s *TestState) PartialForFields(fields [][]any) (restream.Partial, bool) {
	fields = restream.ReduceFieldPaths(fields)
	ret := &TestStatePartial{}
	included := false
	if partial, ok := s.partialForFieldsMapPtrTest(restream.ChildFieldsForField(fields, "MapPtrTest")); ok {
		ret.MapPtrTest = partial
		included = true
	}
	if partial, ok := s.partialForFieldsBaseField(restream.ChildFieldsForField(fields, "BaseField")); ok {
		ret.BaseField = partial
		included = true
	}
	if partial, ok := s.partialForFieldsBaseStruct(restream.ChildFieldsForField(fields, "BaseStruct")); ok {
		ret.BaseStruct = partial
		included = true
	}
	if partial, ok := s.partialForFieldsBaseStructPtr(restream.ChildFieldsForField(fields, "BaseStructPtr")); ok {
		ret.BaseStructPtr = partial
		included = true
	}
	return ret, included
}

func (s *TestState) partialForFieldsMapPtrTest(fields [][]any) (*restream.PartialModMap[uint8, *TestMapData, *TestMapDataPartial], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := restream.NewPartialModMap[uint8, *TestMapData, *TestMapDataPartial]()
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(s.MapPtrTest), true
		}
		key, ok := restream.FieldPathPartToKey[uint8](field[0])
		if !ok {
			continue
		}
		value, exists := s.MapPtrTest[key]
		if !exists {
			ret.Delete(key)
			included = true
			continue
		}
		if len(field) == 1 {
			ret.Set(key, value)
			included = true
			continue
		}
		if value == nil {
			ret.Set(key, value)
			included = true
			continue
		}
		partial, ok := value.PartialForFields([][]any{field[1:]})
		if ok {
			ret.ApplyPartial(key, partial.(*TestMapDataPartial))
			included = true
		}
	}
	return ret, included
}

func (s *TestState) partialForFieldsBaseField(fields [][]any) (*string, bool) {
	if len(fields) == 0 {
		return nil, false
	}
	for _, field := range fields {
		if len(field) == 0 {
			return restream.Ptr(s.BaseField), true
		}
	}
	return nil, false
}

func (s *TestState) partialForFieldsBaseStruct(fields [][]any) (*restream.PartialValue[TestMapData, *TestMapDataPartial], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := &restream.PartialValue[TestMapData, *TestMapDataPartial]{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(restream.Ptr(s.BaseStruct)), true
		}
		partial, ok := (&s.BaseStruct).PartialForFields([][]any{field})
		if ok {
			ret.ApplyPartial(partial.(*TestMapDataPartial))
			included = true
		}
	}
	return ret, included
}

func (s *TestState) partialForFieldsBaseStructPtr(fields [][]any) (*restream.PartialValue[*TestMapData, *TestMapDataPartial], bool) {
	if len(fields) == 0 {
		return nil, false
	}
	ret := &restream.PartialValue[*TestMapData, *TestMapDataPartial]{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return ret.SetWhole(restream.Ptr(s.BaseStructPtr)), true
		}
		if s.BaseStructPtr == nil {
			ret.SetWhole(restream.Ptr(s.BaseStructPtr))
			included = true
			continue
		}
		partial, ok := s.BaseStructPtr.PartialForFields([][]any{field})
		if ok {
			ret.ApplyPartial(partial.(*TestMapDataPartial))
			included = true
		}
	}
	return ret, included
}

// TestStatePartialFieldInfo is the static field info for the TestStatePartial struct
var TestStatePartialFieldInfo = []restream.FieldInfo{
	{Name: "MapPtrTest", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialModMap", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint8}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapDataPartial", Package: "storetest"}}}}}},
	{Name: "BaseField", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeString}}},
	{Name: "BaseStruct", FieldIdx: 2, FieldID: 3, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialValue", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapDataPartial", Package: "storetest"}}}}}},
	{Name: "BaseStructPtr", FieldIdx: 3, FieldID: 4, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialValue", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapData", Package: "storetest"}}, &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "TestMapDataPartial", Package: "storetest"}}}}}},
}

// TestStatePartialFieldMap is the static field map for the TestStatePartial struct
var TestStatePartialFieldMap = map[byte]*restream.FieldInfo{
	1: &TestStatePartialFieldInfo[0],
	2: &TestStatePartialFieldInfo[1],
	3: &TestStatePartialFieldInfo[2],
	4: &TestStatePartialFieldInfo[3],
}

// Serialize serializes this structure to a binary writer
func (s *TestStatePartial) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.MapPtrTest, &TestStatePartialFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.BaseField, &TestStatePartialFieldInfo[1], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.BaseStruct, &TestStatePartialFieldInfo[2], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.BaseStructPtr, &TestStatePartialFieldInfo[3], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *TestStatePartial) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.MapPtrTest,
		&s.BaseField,
		&s.BaseStruct,
		&s.BaseStructPtr,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, TestStatePartialFieldInfo, TestStatePartialFieldMap, fieldPtrs)
}
