// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package main

import (
	"github.com/boatkit-io/restream/pkg/binarystreams"
	"github.com/boatkit-io/restream/pkg/restream"
)

// PlaceTokenRequest is a request object for the PlaceToken RPC call
type PlaceTokenRequest struct { //nolint:revive
	X int
	Y int
}

// PlaceTokenRequestFieldInfo is the static field info for the PlaceTokenRequest struct
var PlaceTokenRequestFieldInfo = []restream.FieldInfo{
	{Name: "X", FieldIdx: 0, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeInt64, MappedType: restream.Ptr("int")}},
	{Name: "Y", FieldIdx: 1, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeInt64, MappedType: restream.Ptr("int")}},
}

// Serialize serializes this structure to a binary writer
func (s *PlaceTokenRequest) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	if err := restream.SerializeValue(s.X, w, PlaceTokenRequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := restream.SerializeValue(s.Y, w, PlaceTokenRequestFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *PlaceTokenRequest) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	if err := restream.DeserializeValue(&s.X, r, PlaceTokenRequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := restream.DeserializeValue(&s.Y, r, PlaceTokenRequestFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}

// PlaceTokenResponse is a response object for the PlaceToken RPC call
type PlaceTokenResponse struct { //nolint:revive
	Error *string
}

// PlaceTokenResponseFieldInfo is the static field info for the PlaceTokenResponse struct
var PlaceTokenResponseFieldInfo = []restream.FieldInfo{
	{Name: "Error", FieldIdx: 0, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeString}}},
}

// Serialize serializes this structure to a binary writer
func (s *PlaceTokenResponse) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	if err := restream.SerializeValue(s.Error, w, PlaceTokenResponseFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *PlaceTokenResponse) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	if err := restream.DeserializeValue(&s.Error, r, PlaceTokenResponseFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}
