// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package main

import (
	"github.com/boatkit-io/restream/pkg/binarystreams"
	"github.com/boatkit-io/restream/pkg/restream"
)

// BoardStoreStateFieldInfo is the static field info for the BoardStoreState struct
var BoardStoreStateFieldInfo = []restream.FieldInfo{
	{Name: "Board", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoArray{NotNil: false, ElemType: &restream.VarInfoArray{NotNil: false, ElemType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeString}}}},
	{Name: "XTurn", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeBool}},
}

// BoardStoreStateFieldMap is the static field map for the BoardStoreState struct
var BoardStoreStateFieldMap = map[byte]*restream.FieldInfo{
	1: &BoardStoreStateFieldInfo[0],
	2: &BoardStoreStateFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *BoardStoreState) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.Board, &BoardStoreStateFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.XTurn, &BoardStoreStateFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *BoardStoreState) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.Board,
		&s.XTurn,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, BoardStoreStateFieldInfo, BoardStoreStateFieldMap, fieldPtrs)
}

// BoardStoreStatePartial is a partial struct for BoardStoreState
type BoardStoreStatePartial struct {
	Board *restream.PartialArray[[]string]
	XTurn *bool
}

// MergeOntoPartial merges this partial onto another partial
func (s *BoardStoreStatePartial) MergeOntoPartial(por any) {
	po := por.(*BoardStoreStatePartial)
	if s.Board != nil {
		if po.Board == nil {
			po.Board = s.Board
		} else {
			s.Board.MergeOntoPartial(po.Board)
		}
	}
	if s.XTurn != nil {
		po.XTurn = s.XTurn
	}
}

// ApplyTo applies this partial to the full version of the struct
func (s *BoardStoreStatePartial) ApplyTo(por any) [][]any {
	po, ok := por.(*BoardStoreState)
	if !ok {
		pop := por.(**BoardStoreState)
		if *pop == nil {
			*pop = &BoardStoreState{}
		}
		po = *pop
	}
	ret := [][]any{}
	if s.Board != nil {
		fs := s.Board.ApplyTo(&po.Board)
		for _, f := range fs {
			ret = append(ret, append(append([]any{}, "Board"), f...))
		}
	}
	if s.XTurn != nil {
		po.XTurn = *s.XTurn
		ret = append(ret, []any{"XTurn"})
	}
	return ret
}

// FilterToFields returns a new partial containing only changes matching the requested field paths
func (s *BoardStoreStatePartial) FilterToFields(fields [][]any) (restream.Partial, bool) {
	ret := &BoardStoreStatePartial{}
	included := false
	for _, field := range fields {
		if len(field) == 0 {
			return s, true
		}
	}
	if s.Board != nil {
		childFields := restream.ChildFieldsForField(fields, "Board")
		if len(childFields) > 0 {
			filtered, ok := restream.FilterPartialToFields(s.Board, childFields)
			if ok {
				ret.Board = filtered
				included = true
			}
		}
	}
	if s.XTurn != nil {
		childFields := restream.ChildFieldsForField(fields, "XTurn")
		if len(childFields) > 0 {
			ret.XTurn = s.XTurn
			included = true
		}
	}
	return ret, included
}

// BoardStoreStatePartialFieldInfo is the static field info for the BoardStoreStatePartial struct
var BoardStoreStatePartialFieldInfo = []restream.FieldInfo{
	{Name: "Board", FieldIdx: 0, FieldID: 1, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoStruct{Name: "PartialArray", Package: "restream", GenericTypes: []restream.VarInfo{&restream.VarInfoArray{NotNil: false, ElemType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeString}}}}}},
	{Name: "XTurn", FieldIdx: 1, FieldID: 2, VarInfo: &restream.VarInfoPointer{NotNil: false, SubType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeBool}}},
}

// BoardStoreStatePartialFieldMap is the static field map for the BoardStoreStatePartial struct
var BoardStoreStatePartialFieldMap = map[byte]*restream.FieldInfo{
	1: &BoardStoreStatePartialFieldInfo[0],
	2: &BoardStoreStatePartialFieldInfo[1],
}

// Serialize serializes this structure to a binary writer
func (s *BoardStoreStatePartial) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	wi, buf := binarystreams.NewMemoryWriter()
	if err := restream.SerializeField(s.Board, &BoardStoreStatePartialFieldInfo[0], wi); err != nil {
		return err
	}
	if err := restream.SerializeField(s.XTurn, &BoardStoreStatePartialFieldInfo[1], wi); err != nil {
		return err
	}
	if err := wi.Flush(); err != nil {
		return err
	}
	b := buf.Bytes()
	if err := restream.SerializePacked64(uint64(len(b)), w); err != nil {
		return err
	}
	return w.WriteBytes(b)
}

// Deserialize deserializes data from a binary reader into this struct
func (s *BoardStoreStatePartial) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	fieldPtrs := []any{
		&s.Board,
		&s.XTurn,
	}
	sl, err := restream.DeserializePacked64[uint64](r)
	if err != nil {
		return err
	}
	ri, err := r.Slice(int(sl))
	if err != nil {
		return err
	}
	return restream.DeserializeFielded(ri, BoardStoreStatePartialFieldInfo, BoardStoreStatePartialFieldMap, fieldPtrs)
}
