// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package restream

import (
	"errors"
	"fmt"
)

const (
	// SerializationTypeInvalid is a SerializationType of type Invalid.
	SerializationTypeInvalid SerializationType = iota
	// SerializationTypeBool is a SerializationType of type Bool.
	SerializationTypeBool
	// SerializationTypeString is a SerializationType of type String.
	SerializationTypeString
	// SerializationTypeInt8 is a SerializationType of type Int8.
	SerializationTypeInt8
	// SerializationTypeInt16 is a SerializationType of type Int16.
	SerializationTypeInt16
	// SerializationTypeInt32 is a SerializationType of type Int32.
	SerializationTypeInt32
	// SerializationTypeInt64 is a SerializationType of type Int64.
	SerializationTypeInt64
	// SerializationTypeUint8 is a SerializationType of type Uint8.
	SerializationTypeUint8
	// SerializationTypeUint16 is a SerializationType of type Uint16.
	SerializationTypeUint16
	// SerializationTypeUint32 is a SerializationType of type Uint32.
	SerializationTypeUint32
	// SerializationTypeUint64 is a SerializationType of type Uint64.
	SerializationTypeUint64
	// SerializationTypeFloat32 is a SerializationType of type Float32.
	SerializationTypeFloat32
	// SerializationTypeFloat64 is a SerializationType of type Float64.
	SerializationTypeFloat64
	// SerializationTypeTime is a SerializationType of type Time.
	SerializationTypeTime
	// SerializationTypePointer is a SerializationType of type Pointer.
	SerializationTypePointer
	// SerializationTypeArray is a SerializationType of type Array.
	SerializationTypeArray
	// SerializationTypeMap is a SerializationType of type Map.
	SerializationTypeMap
	// SerializationTypeDynamic is a SerializationType of type Dynamic.
	SerializationTypeDynamic
	// SerializationTypeVoid is a SerializationType of type Void.
	SerializationTypeVoid
)

var ErrInvalidSerializationType = errors.New("not a valid SerializationType")

const _SerializationTypeName = "InvalidBoolStringInt8Int16Int32Int64Uint8Uint16Uint32Uint64Float32Float64TimePointerArrayMapDynamicVoid"

var _SerializationTypeMap = map[SerializationType]string{
	SerializationTypeInvalid: _SerializationTypeName[0:7],
	SerializationTypeBool:    _SerializationTypeName[7:11],
	SerializationTypeString:  _SerializationTypeName[11:17],
	SerializationTypeInt8:    _SerializationTypeName[17:21],
	SerializationTypeInt16:   _SerializationTypeName[21:26],
	SerializationTypeInt32:   _SerializationTypeName[26:31],
	SerializationTypeInt64:   _SerializationTypeName[31:36],
	SerializationTypeUint8:   _SerializationTypeName[36:41],
	SerializationTypeUint16:  _SerializationTypeName[41:47],
	SerializationTypeUint32:  _SerializationTypeName[47:53],
	SerializationTypeUint64:  _SerializationTypeName[53:59],
	SerializationTypeFloat32: _SerializationTypeName[59:66],
	SerializationTypeFloat64: _SerializationTypeName[66:73],
	SerializationTypeTime:    _SerializationTypeName[73:77],
	SerializationTypePointer: _SerializationTypeName[77:84],
	SerializationTypeArray:   _SerializationTypeName[84:89],
	SerializationTypeMap:     _SerializationTypeName[89:92],
	SerializationTypeDynamic: _SerializationTypeName[92:99],
	SerializationTypeVoid:    _SerializationTypeName[99:103],
}

// String implements the Stringer interface.
func (x SerializationType) String() string {
	if str, ok := _SerializationTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SerializationType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SerializationType) IsValid() bool {
	_, ok := _SerializationTypeMap[x]
	return ok
}

var _SerializationTypeValue = map[string]SerializationType{
	_SerializationTypeName[0:7]:    SerializationTypeInvalid,
	_SerializationTypeName[7:11]:   SerializationTypeBool,
	_SerializationTypeName[11:17]:  SerializationTypeString,
	_SerializationTypeName[17:21]:  SerializationTypeInt8,
	_SerializationTypeName[21:26]:  SerializationTypeInt16,
	_SerializationTypeName[26:31]:  SerializationTypeInt32,
	_SerializationTypeName[31:36]:  SerializationTypeInt64,
	_SerializationTypeName[36:41]:  SerializationTypeUint8,
	_SerializationTypeName[41:47]:  SerializationTypeUint16,
	_SerializationTypeName[47:53]:  SerializationTypeUint32,
	_SerializationTypeName[53:59]:  SerializationTypeUint64,
	_SerializationTypeName[59:66]:  SerializationTypeFloat32,
	_SerializationTypeName[66:73]:  SerializationTypeFloat64,
	_SerializationTypeName[73:77]:  SerializationTypeTime,
	_SerializationTypeName[77:84]:  SerializationTypePointer,
	_SerializationTypeName[84:89]:  SerializationTypeArray,
	_SerializationTypeName[89:92]:  SerializationTypeMap,
	_SerializationTypeName[92:99]:  SerializationTypeDynamic,
	_SerializationTypeName[99:103]: SerializationTypeVoid,
}

// ParseSerializationType attempts to convert a string to a SerializationType.
func ParseSerializationType(name string) (SerializationType, error) {
	if x, ok := _SerializationTypeValue[name]; ok {
		return x, nil
	}
	return SerializationType(0), fmt.Errorf("%s is %w", name, ErrInvalidSerializationType)
}
