// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package restream

import (
	"reflect"

	"github.com/boatkit-io/restream/pkg/binarystreams"
)

// PartialMapFieldInfo is the static field info for the PartialMap struct
var PartialMapFieldInfo = []FieldInfo{
	{Name: "dataSets", FieldIdx: 0, VarInfo: &VarInfoMap{NotNil: true, KeyType: &VarInfoGenericParam{Name: "K"}, ElemType: &VarInfoGenericParam{Name: "V"}}},
	{Name: "dataDeletes", FieldIdx: 1, VarInfo: &VarInfoMap{NotNil: true, KeyType: &VarInfoGenericParam{Name: "K"}}},
	{Name: "whole", FieldIdx: 2, VarInfo: &VarInfoMap{NotNil: false, KeyType: &VarInfoGenericParam{Name: "K"}, ElemType: &VarInfoGenericParam{Name: "V"}}},
}

// GetTypeArgs returns the type arguments for this struct
func (s *PartialMap[K, V]) GetTypeArgs() []VarInfo {
	vis := []VarInfo{}
	var vi VarInfo
	var err error
	vi, err = VarInfoFromType(reflect.TypeFor[K]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	vi, err = VarInfoFromType(reflect.TypeFor[V]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	return vis
}

// Serialize serializes this structure to a binary writer
func (s *PartialMap[K, V]) Serialize(w *binarystreams.Writer, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"K": vi.GenericTypes[0],
		"V": vi.GenericTypes[1],
	}
	if err := SerializeValue(s.dataSets, w, PartialMapFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := SerializeValue(s.dataDeletes, w, PartialMapFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := SerializeValue(s.whole, w, PartialMapFieldInfo[2].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *PartialMap[K, V]) Deserialize(r *binarystreams.Reader, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"K": vi.GenericTypes[0],
		"V": vi.GenericTypes[1],
	}
	if err := DeserializeValue(&s.dataSets, r, PartialMapFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := DeserializeValue(&s.dataDeletes, r, PartialMapFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := DeserializeValue(&s.whole, r, PartialMapFieldInfo[2].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}

// PartialModMapFieldInfo is the static field info for the PartialModMap struct
var PartialModMapFieldInfo = []FieldInfo{
	{Name: "dataSets", FieldIdx: 0, VarInfo: &VarInfoMap{NotNil: true, KeyType: &VarInfoGenericParam{Name: "K"}, ElemType: &VarInfoGenericParam{Name: "V"}}},
	{Name: "dataDeletes", FieldIdx: 1, VarInfo: &VarInfoMap{NotNil: true, KeyType: &VarInfoGenericParam{Name: "K"}}},
	{Name: "dataMods", FieldIdx: 2, VarInfo: &VarInfoMap{NotNil: true, KeyType: &VarInfoGenericParam{Name: "K"}, ElemType: &VarInfoGenericParam{Name: "P"}}},
	{Name: "whole", FieldIdx: 3, VarInfo: &VarInfoMap{NotNil: false, KeyType: &VarInfoGenericParam{Name: "K"}, ElemType: &VarInfoGenericParam{Name: "V"}}},
}

// GetTypeArgs returns the type arguments for this struct
func (s *PartialModMap[K, V, P]) GetTypeArgs() []VarInfo {
	vis := []VarInfo{}
	var vi VarInfo
	var err error
	vi, err = VarInfoFromType(reflect.TypeFor[K]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	vi, err = VarInfoFromType(reflect.TypeFor[V]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	vi, err = VarInfoFromType(reflect.TypeFor[P]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	return vis
}

// Serialize serializes this structure to a binary writer
func (s *PartialModMap[K, V, P]) Serialize(w *binarystreams.Writer, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"K": vi.GenericTypes[0],
		"V": vi.GenericTypes[1],
		"P": vi.GenericTypes[2],
	}
	if err := SerializeValue(s.dataSets, w, PartialModMapFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := SerializeValue(s.dataDeletes, w, PartialModMapFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := SerializeValue(s.dataMods, w, PartialModMapFieldInfo[2].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := SerializeValue(s.whole, w, PartialModMapFieldInfo[3].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *PartialModMap[K, V, P]) Deserialize(r *binarystreams.Reader, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"K": vi.GenericTypes[0],
		"V": vi.GenericTypes[1],
		"P": vi.GenericTypes[2],
	}
	if err := DeserializeValue(&s.dataSets, r, PartialModMapFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := DeserializeValue(&s.dataDeletes, r, PartialModMapFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := DeserializeValue(&s.dataMods, r, PartialModMapFieldInfo[2].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := DeserializeValue(&s.whole, r, PartialModMapFieldInfo[3].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}
