// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package restream

import (
	"reflect"

	"github.com/boatkit-io/restream/pkg/binarystreams"
)

// PartialValueFieldInfo is the static field info for the PartialValue struct
var PartialValueFieldInfo = []FieldInfo{
	{Name: "whole", FieldIdx: 0, VarInfo: &VarInfoPointer{NotNil: false, SubType: &VarInfoGenericParam{Name: "V"}}},
	{Name: "partial", FieldIdx: 1, VarInfo: &VarInfoPointer{NotNil: false, SubType: &VarInfoGenericParam{Name: "P"}}},
}

// GetTypeArgs returns the type arguments for this struct
func (s *PartialValue[V, P]) GetTypeArgs() []VarInfo {
	vis := []VarInfo{}
	var vi VarInfo
	var err error
	vi, err = VarInfoFromType(reflect.TypeFor[V]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	vi, err = VarInfoFromType(reflect.TypeFor[P]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	return vis
}

// Serialize serializes this structure to a binary writer
func (s *PartialValue[V, P]) Serialize(w *binarystreams.Writer, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"V": vi.GenericTypes[0],
		"P": vi.GenericTypes[1],
	}
	if err := SerializeValue(s.whole, w, PartialValueFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := SerializeValue(s.partial, w, PartialValueFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *PartialValue[V, P]) Deserialize(r *binarystreams.Reader, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"V": vi.GenericTypes[0],
		"P": vi.GenericTypes[1],
	}
	if err := DeserializeValue(&s.whole, r, PartialValueFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := DeserializeValue(&s.partial, r, PartialValueFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}
