// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package restream

import (
	"reflect"

	"github.com/boatkit-io/restream/pkg/binarystreams"
)

// PartialArrayFieldInfo is the static field info for the PartialArray struct
var PartialArrayFieldInfo = []FieldInfo{
	{Name: "dataSets", FieldIdx: 0, VarInfo: &VarInfoMap{NotNil: true, KeyType: &VarInfoPrimitive{DataType: SerializationTypeInt64, MappedType: Ptr("int")}, ElemType: &VarInfoGenericParam{Name: "V"}}},
	{Name: "whole", FieldIdx: 1, VarInfo: &VarInfoArray{NotNil: false, ElemType: &VarInfoGenericParam{Name: "V"}}},
}

// GetTypeArgs returns the type arguments for this struct
func (s *PartialArray[V]) GetTypeArgs() []VarInfo {
	vis := []VarInfo{}
	var vi VarInfo
	var err error
	vi, err = VarInfoFromType(reflect.TypeFor[V]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	return vis
}

// Serialize serializes this structure to a binary writer
func (s *PartialArray[V]) Serialize(w *binarystreams.Writer, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"V": vi.GenericTypes[0],
	}
	if err := SerializeValue(s.dataSets, w, PartialArrayFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := SerializeValue(s.whole, w, PartialArrayFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *PartialArray[V]) Deserialize(r *binarystreams.Reader, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"V": vi.GenericTypes[0],
	}
	if err := DeserializeValue(&s.dataSets, r, PartialArrayFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := DeserializeValue(&s.whole, r, PartialArrayFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}

// PartialModArrayFieldInfo is the static field info for the PartialModArray struct
var PartialModArrayFieldInfo = []FieldInfo{
	{Name: "dataSets", FieldIdx: 0, VarInfo: &VarInfoMap{NotNil: true, KeyType: &VarInfoPrimitive{DataType: SerializationTypeInt64, MappedType: Ptr("int")}, ElemType: &VarInfoGenericParam{Name: "V"}}},
	{Name: "dataMods", FieldIdx: 1, VarInfo: &VarInfoMap{NotNil: true, KeyType: &VarInfoPrimitive{DataType: SerializationTypeInt64, MappedType: Ptr("int")}, ElemType: &VarInfoGenericParam{Name: "P"}}},
	{Name: "whole", FieldIdx: 2, VarInfo: &VarInfoArray{NotNil: false, ElemType: &VarInfoGenericParam{Name: "V"}}},
}

// GetTypeArgs returns the type arguments for this struct
func (s *PartialModArray[V, P]) GetTypeArgs() []VarInfo {
	vis := []VarInfo{}
	var vi VarInfo
	var err error
	vi, err = VarInfoFromType(reflect.TypeFor[V]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	vi, err = VarInfoFromType(reflect.TypeFor[P]())
	if err != nil {
		panic(err)
	}
	vis = append(vis, vi)
	return vis
}

// Serialize serializes this structure to a binary writer
func (s *PartialModArray[V, P]) Serialize(w *binarystreams.Writer, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"V": vi.GenericTypes[0],
		"P": vi.GenericTypes[1],
	}
	if err := SerializeValue(s.dataSets, w, PartialModArrayFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := SerializeValue(s.dataMods, w, PartialModArrayFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := SerializeValue(s.whole, w, PartialModArrayFieldInfo[2].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *PartialModArray[V, P]) Deserialize(r *binarystreams.Reader, vi *VarInfoStruct) error {
	gm := map[string]VarInfo{
		"V": vi.GenericTypes[0],
		"P": vi.GenericTypes[1],
	}
	if err := DeserializeValue(&s.dataSets, r, PartialModArrayFieldInfo[0].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := DeserializeValue(&s.dataMods, r, PartialModArrayFieldInfo[1].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	if err := DeserializeValue(&s.whole, r, PartialModArrayFieldInfo[2].VarInfo.FillGenerics(gm)); err != nil {
		return err
	}
	return nil
}
