// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package restream

import (
	"github.com/boatkit-io/restream/pkg/binarystreams"
)

// LatLongFieldInfo is the static field info for the LatLong struct
var LatLongFieldInfo = []FieldInfo{
	{Name: "Lat", FieldIdx: 0, VarInfo: &VarInfoPrimitive{DataType: SerializationTypeFloat64}},
	{Name: "Long", FieldIdx: 1, VarInfo: &VarInfoPrimitive{DataType: SerializationTypeFloat64}},
}

// Serialize serializes this structure to a binary writer
func (s *LatLong) Serialize(w *binarystreams.Writer, _ *VarInfoStruct) error {
	if err := SerializeValue(s.Lat, w, LatLongFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := SerializeValue(s.Long, w, LatLongFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *LatLong) Deserialize(r *binarystreams.Reader, _ *VarInfoStruct) error {
	if err := DeserializeValue(&s.Lat, r, LatLongFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := DeserializeValue(&s.Long, r, LatLongFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}

// RestreamClone returns a deep copy of this LatLong.
func (s *LatLong) RestreamClone() *LatLong {
	if s == nil {
		return nil
	}
	ret := &LatLong{}
	ret.Lat = s.Lat
	ret.Long = s.Long
	return ret
}

// callRequest is a request object for the call RPC call
type callRequest struct { //nolint:revive
	Test int
}

// callRequestFieldInfo is the static field info for the callRequest struct
var callRequestFieldInfo = []FieldInfo{
	{Name: "Test", FieldIdx: 0, VarInfo: &VarInfoPrimitive{DataType: SerializationTypeInt64, MappedType: Ptr("int")}},
}

// Serialize serializes this structure to a binary writer
func (s *callRequest) Serialize(w *binarystreams.Writer, _ *VarInfoStruct) error {
	if err := SerializeValue(s.Test, w, callRequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *callRequest) Deserialize(r *binarystreams.Reader, _ *VarInfoStruct) error {
	if err := DeserializeValue(&s.Test, r, callRequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}

// callResponse is a response object for the call RPC call
type callResponse struct { //nolint:revive
	Result int
	Error  *string
}

// callResponseFieldInfo is the static field info for the callResponse struct
var callResponseFieldInfo = []FieldInfo{
	{Name: "Result", FieldIdx: 0, VarInfo: &VarInfoPrimitive{DataType: SerializationTypeInt64, MappedType: Ptr("int")}},
	{Name: "Error", FieldIdx: 1, VarInfo: &VarInfoPointer{NotNil: false, SubType: &VarInfoPrimitive{DataType: SerializationTypeString}}},
}

// Serialize serializes this structure to a binary writer
func (s *callResponse) Serialize(w *binarystreams.Writer, _ *VarInfoStruct) error {
	if err := SerializeValue(s.Result, w, callResponseFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := SerializeValue(s.Error, w, callResponseFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *callResponse) Deserialize(r *binarystreams.Reader, _ *VarInfoStruct) error {
	if err := DeserializeValue(&s.Result, r, callResponseFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := DeserializeValue(&s.Error, r, callResponseFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}

// call2Request is a request object for the call2 RPC call
type call2Request struct { //nolint:revive
	Test LatLong
}

// call2RequestFieldInfo is the static field info for the call2Request struct
var call2RequestFieldInfo = []FieldInfo{
	{Name: "Test", FieldIdx: 0, VarInfo: &VarInfoStruct{Name: "LatLong", Package: "restream"}},
}

// Serialize serializes this structure to a binary writer
func (s *call2Request) Serialize(w *binarystreams.Writer, _ *VarInfoStruct) error {
	if err := SerializeValue(&s.Test, w, call2RequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *call2Request) Deserialize(r *binarystreams.Reader, _ *VarInfoStruct) error {
	if err := DeserializeValue(&s.Test, r, call2RequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}

// call2Response is a response object for the call2 RPC call
type call2Response struct { //nolint:revive
	Result *int
	Error  *string
}

// call2ResponseFieldInfo is the static field info for the call2Response struct
var call2ResponseFieldInfo = []FieldInfo{
	{Name: "Result", FieldIdx: 0, VarInfo: &VarInfoPointer{NotNil: false, SubType: &VarInfoPrimitive{DataType: SerializationTypeInt64, MappedType: Ptr("int")}}},
	{Name: "Error", FieldIdx: 1, VarInfo: &VarInfoPointer{NotNil: false, SubType: &VarInfoPrimitive{DataType: SerializationTypeString}}},
}

// Serialize serializes this structure to a binary writer
func (s *call2Response) Serialize(w *binarystreams.Writer, _ *VarInfoStruct) error {
	if err := SerializeValue(s.Result, w, call2ResponseFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := SerializeValue(s.Error, w, call2ResponseFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *call2Response) Deserialize(r *binarystreams.Reader, _ *VarInfoStruct) error {
	if err := DeserializeValue(&s.Result, r, call2ResponseFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := DeserializeValue(&s.Error, r, call2ResponseFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}

// call3Request is a request object for the call3 RPC call
type call3Request struct { //nolint:revive
	Test []int
}

// call3RequestFieldInfo is the static field info for the call3Request struct
var call3RequestFieldInfo = []FieldInfo{
	{Name: "Test", FieldIdx: 0, VarInfo: &VarInfoArray{NotNil: false, ElemType: &VarInfoPrimitive{DataType: SerializationTypeInt64, MappedType: Ptr("int")}}},
}

// Serialize serializes this structure to a binary writer
func (s *call3Request) Serialize(w *binarystreams.Writer, _ *VarInfoStruct) error {
	if err := SerializeValue(s.Test, w, call3RequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *call3Request) Deserialize(r *binarystreams.Reader, _ *VarInfoStruct) error {
	if err := DeserializeValue(&s.Test, r, call3RequestFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}

// call3Response is a response object for the call3 RPC call
type call3Response struct { //nolint:revive
	Result *int
	Error  *string
}

// call3ResponseFieldInfo is the static field info for the call3Response struct
var call3ResponseFieldInfo = []FieldInfo{
	{Name: "Result", FieldIdx: 0, VarInfo: &VarInfoPointer{NotNil: false, SubType: &VarInfoPrimitive{DataType: SerializationTypeInt64, MappedType: Ptr("int")}}},
	{Name: "Error", FieldIdx: 1, VarInfo: &VarInfoPointer{NotNil: false, SubType: &VarInfoPrimitive{DataType: SerializationTypeString}}},
}

// Serialize serializes this structure to a binary writer
func (s *call3Response) Serialize(w *binarystreams.Writer, _ *VarInfoStruct) error {
	if err := SerializeValue(s.Result, w, call3ResponseFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := SerializeValue(s.Error, w, call3ResponseFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *call3Response) Deserialize(r *binarystreams.Reader, _ *VarInfoStruct) error {
	if err := DeserializeValue(&s.Result, r, call3ResponseFieldInfo[0].VarInfo); err != nil {
		return err
	}
	if err := DeserializeValue(&s.Error, r, call3ResponseFieldInfo[1].VarInfo); err != nil {
		return err
	}
	return nil
}
