package restream

// Store is a basic interface for a store, to be tracked by the StoreRegistry
type Store interface {
	GetName() string
	GetStoreData() StoreDataBase
	SubscribeToField(field []any, callback any)
	GetStoreType() StoreType
}

// StoreType describes where a store is implemented and whether device state should stream to a cloud relay.
type StoreType int

const (
	// StoreTypeDeviceWithRelay is a device-side store with an autogenerated cloud relay store.
	StoreTypeDeviceWithRelay StoreType = iota
	// StoreTypeDeviceWithNoRelay is a device-side store that should not stream state to a cloud relay.
	StoreTypeDeviceWithNoRelay
	// StoreTypeDeviceWithCloudImpl is a device-side store that streams state to a custom cloud implementation.
	StoreTypeDeviceWithCloudImpl
	// StoreTypeCloudOnly is a cloud-side store with no device-originated relay state.
	StoreTypeCloudOnly
	// StoreTypeCloudImplOfDevice is a cloud-side implementation of a DeviceWithCloudImpl store.
	StoreTypeCloudImplOfDevice
	// StoreTypeDeviceAndCloud is a store implementation used independently on both device and cloud.
	StoreTypeDeviceAndCloud
)

// MinimumAccessLevelStore is optionally implemented by stores that require more than public access to read or subscribe.
type MinimumAccessLevelStore interface {
	GetMinimumAccessLevel() AccessLevel
}

// SubscriptionAwareStore is a deeper interface for a store that cares about being subscription-aware
type SubscriptionAwareStore interface {
	SubscriptionStarted()
	SubscriptionEnded()
}

// KeySubscriptionAwareStore is implemented by stores that want per-subscription-key lifecycle callbacks.
type KeySubscriptionAwareStore interface {
	SubscriptionStartedForKey(key string)
	SubscriptionEndedForKey(key string)
}

// StateFieldPartialProvider is implemented by generated state structs that can create a partial snapshot for field paths.
type StateFieldPartialProvider interface {
	PartialForFields(fields [][]any) (Partial, bool)
}

// StoreTypeForStore returns the store type for a store, defaulting nil to a device store with relay support.
func StoreTypeForStore(store Store) StoreType {
	if store == nil {
		return StoreTypeDeviceWithRelay
	}
	return store.GetStoreType()
}

// StoreTypeStreamsToRelay reports whether device state for the type should be sent to a cloud relay.
func StoreTypeStreamsToRelay(storeType StoreType) bool {
	return storeType == StoreTypeDeviceWithRelay || storeType == StoreTypeDeviceWithCloudImpl
}
