// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
//
//nolint:lll
package keyedevents

import (
	"github.com/boatkit-io/restream/pkg/binarystreams"
	"github.com/boatkit-io/restream/pkg/restream"
)

// RadioAudioEvent is an event packet object for the Radio.Audio event
type RadioAudioEvent struct { //nolint:revive
	Audio []uint8
}

// RadioAudioEventFieldInfo is the static field info for the RadioAudioEvent struct
var RadioAudioEventFieldInfo = []restream.FieldInfo{
	{Name: "Audio", FieldIdx: 0, VarInfo: &restream.VarInfoArray{NotNil: false, ElemType: &restream.VarInfoPrimitive{DataType: restream.SerializationTypeUint8}}},
}

// Serialize serializes this structure to a binary writer
func (s *RadioAudioEvent) Serialize(w *binarystreams.Writer, _ *restream.VarInfoStruct) error {
	if err := restream.SerializeValue(s.Audio, w, RadioAudioEventFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}

// Deserialize deserializes data from a binary reader into this struct
func (s *RadioAudioEvent) Deserialize(r *binarystreams.Reader, _ *restream.VarInfoStruct) error {
	if err := restream.DeserializeValue(&s.Audio, r, RadioAudioEventFieldInfo[0].VarInfo); err != nil {
		return err
	}
	return nil
}
