// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
 
 
import BinaryReader from '../utils/BinaryReader.js';
import BinaryWriter from '../utils/BinaryWriter.js';
import * as ReStreamDecoders from '../utils/Decoders.js';
import * as ReStreamEncoders from '../utils/Encoders.js';
import { SerializationType, VarInfoArray, VarInfoPointer, VarInfoPrimitive, VarInfoStruct } from '../utils/SerializationTypes.js';
import type { FieldInfo } from '../utils/SerializationTypes.js';
import { EventStruct, RPCStruct } from '../websocket/SocketHelper.js';

export const AccessLevelAdmin = 2;

export const AccessLevelViewer = 1;

export const viewerSocketTestStoreName = "test-store";

export class LatLong {
    public lat!: number;
    public long!: number;

    private constructor() {}

    public static fromValues(
        lat: number = 0,
        long: number = 0,
    ) {
        const o = new LatLong();
        o.lat = lat;
        o.long = long;
        return o;
    }

    public static deserialized(r: BinaryReader, _: VarInfoStruct | undefined) {
        const o = new LatLong();
        o.lat = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo);
        o.long = ReStreamDecoders.deserializeValue(r, this._fieldInfo[1].varInfo);
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        ReStreamEncoders.serializeValue(this.lat, w, LatLong._fieldInfo[0].varInfo);
        ReStreamEncoders.serializeValue(this.long, w, LatLong._fieldInfo[1].varInfo);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Lat", fieldIdx: 0, varInfo: new VarInfoPrimitive(SerializationType.Float64)},
        {name: "Long", fieldIdx: 1, varInfo: new VarInfoPrimitive(SerializationType.Float64)},
	];
}

export class call2Event extends EventStruct {
    public test!: number;

    public static readonly eventBoundName = "call2";
    private constructor() { super(call2Event.eventBoundName); }

    public static fromValues(
        test: number = 0,
    ) {
        const o = new call2Event();
        o.test = test;
        return o;
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Test", fieldIdx: 0, varInfo: new VarInfoPrimitive(SerializationType.Int64, "int")},
	];
    public static deserialized(r: BinaryReader, _: VarInfoStruct | undefined) {
        const o = new call2Event();
        o.test = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo);
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        ReStreamEncoders.serializeValue(this.test, w, call2Event._fieldInfo[0].varInfo);
    }
}

export class call2Request extends RPCStruct<call2Response,number|undefined> {
    public test!: LatLong;
    private constructor() { super("call2", call2Response); }

    public static fromValues(
        test: LatLong = LatLong.fromValues(),
    ) {
        const o = new call2Request();
        o.test = test;
        return o;
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Test", fieldIdx: 0, varInfo: new VarInfoStruct("LatLong", "restream", LatLong)},
	];
    public static deserialized(r: BinaryReader, _: VarInfoStruct | undefined) {
        const o = new call2Request();
        o.test = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo);
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        ReStreamEncoders.serializeValue(this.test, w, call2Request._fieldInfo[0].varInfo);
    }
}

export class call2Response {
    public result!: number|undefined;
    public error!: string|undefined;

    private constructor() {}

    public static fromValues(
        result: number|undefined = undefined,
        error: string|undefined = undefined,
    ) {
        const o = new call2Response();
        o.result = result;
        o.error = error;
        return o;
    }

    public static deserialized(r: BinaryReader, _: VarInfoStruct | undefined) {
        const o = new call2Response();
        o.result = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo);
        o.error = ReStreamDecoders.deserializeValue(r, this._fieldInfo[1].varInfo);
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        ReStreamEncoders.serializeValue(this.result, w, call2Response._fieldInfo[0].varInfo);
        ReStreamEncoders.serializeValue(this.error, w, call2Response._fieldInfo[1].varInfo);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Result", fieldIdx: 0, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.Int64, "int"))},
        {name: "Error", fieldIdx: 1, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.String))},
	];
}

export class call3Request extends RPCStruct<call3Response,number|undefined> {
    public test!: number[]|undefined;
    private constructor() { super("call3", call3Response); }

    public static fromValues(
        test: number[]|undefined = [],
    ) {
        const o = new call3Request();
        o.test = test;
        return o;
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Test", fieldIdx: 0, varInfo: new VarInfoArray(false, new VarInfoPrimitive(SerializationType.Int64, "int"))},
	];
    public static deserialized(r: BinaryReader, _: VarInfoStruct | undefined) {
        const o = new call3Request();
        o.test = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo);
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        ReStreamEncoders.serializeValue(this.test, w, call3Request._fieldInfo[0].varInfo);
    }
}

export class call3Response {
    public result!: number|undefined;
    public error!: string|undefined;

    private constructor() {}

    public static fromValues(
        result: number|undefined = undefined,
        error: string|undefined = undefined,
    ) {
        const o = new call3Response();
        o.result = result;
        o.error = error;
        return o;
    }

    public static deserialized(r: BinaryReader, _: VarInfoStruct | undefined) {
        const o = new call3Response();
        o.result = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo);
        o.error = ReStreamDecoders.deserializeValue(r, this._fieldInfo[1].varInfo);
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        ReStreamEncoders.serializeValue(this.result, w, call3Response._fieldInfo[0].varInfo);
        ReStreamEncoders.serializeValue(this.error, w, call3Response._fieldInfo[1].varInfo);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Result", fieldIdx: 0, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.Int64, "int"))},
        {name: "Error", fieldIdx: 1, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.String))},
	];
}

export class callEvent extends EventStruct {
    public test!: number;

    public static readonly eventBoundName = "call";
    private constructor() { super(callEvent.eventBoundName); }

    public static fromValues(
        test: number = 0,
    ) {
        const o = new callEvent();
        o.test = test;
        return o;
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Test", fieldIdx: 0, varInfo: new VarInfoPrimitive(SerializationType.Int64, "int")},
	];
    public static deserialized(r: BinaryReader, _: VarInfoStruct | undefined) {
        const o = new callEvent();
        o.test = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo);
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        ReStreamEncoders.serializeValue(this.test, w, callEvent._fieldInfo[0].varInfo);
    }
}

export class callRequest extends RPCStruct<callResponse,number> {
    public test!: number;
    private constructor() { super("call", callResponse); }

    public static fromValues(
        test: number = 0,
    ) {
        const o = new callRequest();
        o.test = test;
        return o;
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Test", fieldIdx: 0, varInfo: new VarInfoPrimitive(SerializationType.Int64, "int")},
	];
    public static deserialized(r: BinaryReader, _: VarInfoStruct | undefined) {
        const o = new callRequest();
        o.test = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo);
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        ReStreamEncoders.serializeValue(this.test, w, callRequest._fieldInfo[0].varInfo);
    }
}

export class callResponse {
    public result!: number;
    public error!: string|undefined;

    private constructor() {}

    public static fromValues(
        result: number = 0,
        error: string|undefined = undefined,
    ) {
        const o = new callResponse();
        o.result = result;
        o.error = error;
        return o;
    }

    public static deserialized(r: BinaryReader, _: VarInfoStruct | undefined) {
        const o = new callResponse();
        o.result = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo);
        o.error = ReStreamDecoders.deserializeValue(r, this._fieldInfo[1].varInfo);
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        ReStreamEncoders.serializeValue(this.result, w, callResponse._fieldInfo[0].varInfo);
        ReStreamEncoders.serializeValue(this.error, w, callResponse._fieldInfo[1].varInfo);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Result", fieldIdx: 0, varInfo: new VarInfoPrimitive(SerializationType.Int64, "int")},
        {name: "Error", fieldIdx: 1, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.String))},
	];
}
