// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
 
 
import BinaryReader from '../utils/BinaryReader.js';
import BinaryWriter from '../utils/BinaryWriter.js';
import * as ReStreamDecoders from '../utils/Decoders.js';
import * as ReStreamEncoders from '../utils/Encoders.js';
import { VarInfoPrimitive, VarInfoStruct, VarInfoPointer, VarInfoMap, SerializationType } from '../utils/SerializationTypes.js';
import type { FieldInfo } from '../utils/SerializationTypes.js';
import { PartialValue, PartialModMap } from './PackageRestream.js';

export type TestString = string;

export class TestC {
    public a!: number;
    public b!: number;

    private constructor() {}

    public static fromValues(
        a: number = 0,
        b: number = 0,
    ) {
        const o = new TestC();
        o.a = a;
        o.b = b;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestC._fieldMap);
        }
        const o = new TestC();
        o.a = fieldMap?.has(1) ? fieldMap.get(1) as number : 0;
        o.b = fieldMap?.has(2) ? fieldMap.get(2) as number : 0;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.a, TestC._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.b, TestC._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "A", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPrimitive(SerializationType.Int64, "int")},
        {name: "B", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPrimitive(SerializationType.Int64, "int")},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);
}

export class TestCPartial {
    public a!: number|undefined;
    public b!: number|undefined;

    private constructor() {}

    public static fromValues(
        a: number|undefined = undefined,
        b: number|undefined = undefined,
    ) {
        const o = new TestCPartial();
        o.a = a;
        o.b = b;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestCPartial._fieldMap);
        }
        const o = new TestCPartial();
        o.a = fieldMap?.has(1) ? fieldMap.get(1) as number|undefined : undefined;
        o.b = fieldMap?.has(2) ? fieldMap.get(2) as number|undefined : undefined;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.a, TestCPartial._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.b, TestCPartial._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "A", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.Int64, "int"))},
        {name: "B", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.Int64, "int"))},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);

    applyTo(por: TestC): (string | number)[][] {
        const ret: (string | number)[][] = [];
        if (this.a !== undefined) { por.a = this.a; ret.push(["a"]); }
        if (this.b !== undefined) { por.b = this.b; ret.push(["b"]); }
        return ret;
    }
}

export class TestMapData {
    public number!: number;

    private constructor() {}

    public static fromValues(
        number: number = 0,
    ) {
        const o = new TestMapData();
        o.number = number;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestMapData._fieldMap);
        }
        const o = new TestMapData();
        o.number = fieldMap?.has(1) ? fieldMap.get(1) as number : 0;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.number, TestMapData._fieldInfo[0], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Number", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPrimitive(SerializationType.Uint64, "uint")},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
	]);
}

export class TestMapDataPartial {
    public number!: number|undefined;

    private constructor() {}

    public static fromValues(
        number: number|undefined = undefined,
    ) {
        const o = new TestMapDataPartial();
        o.number = number;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestMapDataPartial._fieldMap);
        }
        const o = new TestMapDataPartial();
        o.number = fieldMap?.has(1) ? fieldMap.get(1) as number|undefined : undefined;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.number, TestMapDataPartial._fieldInfo[0], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Number", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.Uint64, "uint"))},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
	]);

    applyTo(por: TestMapData): (string | number)[][] {
        const ret: (string | number)[][] = [];
        if (this.number !== undefined) { por.number = this.number; ret.push(["number"]); }
        return ret;
    }
}

export class TestPrimitiveOptionalState {
    public primitive!: number;
    public optional!: number|undefined;

    private constructor() {}

    public static fromValues(
        primitive: number = 0,
        optional: number|undefined = undefined,
    ) {
        const o = new TestPrimitiveOptionalState();
        o.primitive = primitive;
        o.optional = optional;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestPrimitiveOptionalState._fieldMap);
        }
        const o = new TestPrimitiveOptionalState();
        o.primitive = fieldMap?.has(1) ? fieldMap.get(1) as number : 0;
        o.optional = fieldMap?.has(2) ? fieldMap.get(2) as number|undefined : undefined;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.primitive, TestPrimitiveOptionalState._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.optional, TestPrimitiveOptionalState._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Primitive", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPrimitive(SerializationType.Uint32)},
        {name: "Optional", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.Uint32))},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);
}

export class TestPrimitiveOptionalStatePartial {
    public primitive!: number|undefined;
    public optional!: number|null|undefined;

    private constructor() {}

    public static fromValues(
        primitive: number|undefined = undefined,
        optional: number|null|undefined = undefined,
    ) {
        const o = new TestPrimitiveOptionalStatePartial();
        o.primitive = primitive;
        o.optional = optional;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestPrimitiveOptionalStatePartial._fieldMap);
        }
        const o = new TestPrimitiveOptionalStatePartial();
        o.primitive = fieldMap?.has(1) ? fieldMap.get(1) as number|undefined : undefined;
        o.optional = fieldMap?.has(2) ? fieldMap.get(2) as number|null|undefined : undefined;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.primitive, TestPrimitiveOptionalStatePartial._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.optional, TestPrimitiveOptionalStatePartial._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Primitive", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.Uint32))},
        {name: "Optional", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPointer(false, new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.Uint32)))},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);

    applyTo(por: TestPrimitiveOptionalState): (string | number)[][] {
        const ret: (string | number)[][] = [];
        if (this.primitive !== undefined) { por.primitive = this.primitive; ret.push(["primitive"]); }
        if (this.optional !== undefined) { por.optional = this.optional === null ? undefined : this.optional; ret.push(["optional"]); }
        return ret;
    }
}

export class TestState {
    public mapPtrTest!: Map<number,TestMapData|undefined>|undefined;
    public baseField!: string;
    public baseStruct!: TestMapData;
    public baseStructPtr!: TestMapData|undefined;

    private constructor() {}

    public static fromValues(
        mapPtrTest: Map<number,TestMapData|undefined>|undefined = undefined,
        baseField: string = "",
        baseStruct: TestMapData = TestMapData.fromValues(),
        baseStructPtr: TestMapData|undefined = undefined,
    ) {
        const o = new TestState();
        o.mapPtrTest = mapPtrTest;
        o.baseField = baseField;
        o.baseStruct = baseStruct;
        o.baseStructPtr = baseStructPtr;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestState._fieldMap);
        }
        const o = new TestState();
        o.mapPtrTest = fieldMap?.has(1) ? fieldMap.get(1) as Map<number,TestMapData|undefined>|undefined : undefined;
        o.baseField = fieldMap?.has(2) ? fieldMap.get(2) as string : "";
        o.baseStruct = fieldMap?.has(3) ? fieldMap.get(3) as TestMapData : TestMapData.fromValues();
        o.baseStructPtr = fieldMap?.has(4) ? fieldMap.get(4) as TestMapData|undefined : undefined;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.mapPtrTest, TestState._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.baseField, TestState._fieldInfo[1], wi);
        ReStreamEncoders.serializeField(this.baseStruct, TestState._fieldInfo[2], wi);
        ReStreamEncoders.serializeField(this.baseStructPtr, TestState._fieldInfo[3], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "MapPtrTest", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoMap(false, new VarInfoPrimitive(SerializationType.Uint8), new VarInfoPointer(false, new VarInfoStruct("TestMapData", "storetest", TestMapData)))},
        {name: "BaseField", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPrimitive(SerializationType.String)},
        {name: "BaseStruct", fieldIdx: 2, fieldID: 3, varInfo: new VarInfoStruct("TestMapData", "storetest", TestMapData)},
        {name: "BaseStructPtr", fieldIdx: 3, fieldID: 4, varInfo: new VarInfoPointer(false, new VarInfoStruct("TestMapData", "storetest", TestMapData))},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
        [3, this._fieldInfo[2]],
        [4, this._fieldInfo[3]],
	]);
}

export class TestStatePartial {
    public mapPtrTest!: PartialModMap<number, TestMapData|undefined, TestMapDataPartial>|undefined;
    public baseField!: string|undefined;
    public baseStruct!: PartialValue<TestMapData, TestMapDataPartial>|undefined;
    public baseStructPtr!: PartialValue<TestMapData|undefined, TestMapDataPartial>|undefined;

    private constructor() {}

    public static fromValues(
        mapPtrTest: PartialModMap<number, TestMapData|undefined, TestMapDataPartial>|undefined = undefined,
        baseField: string|undefined = undefined,
        baseStruct: PartialValue<TestMapData, TestMapDataPartial>|undefined = undefined,
        baseStructPtr: PartialValue<TestMapData|undefined, TestMapDataPartial>|undefined = undefined,
    ) {
        const o = new TestStatePartial();
        o.mapPtrTest = mapPtrTest;
        o.baseField = baseField;
        o.baseStruct = baseStruct;
        o.baseStructPtr = baseStructPtr;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestStatePartial._fieldMap);
        }
        const o = new TestStatePartial();
        o.mapPtrTest = fieldMap?.has(1) ? fieldMap.get(1) as PartialModMap<number, TestMapData|undefined, TestMapDataPartial>|undefined : undefined;
        o.baseField = fieldMap?.has(2) ? fieldMap.get(2) as string|undefined : undefined;
        o.baseStruct = fieldMap?.has(3) ? fieldMap.get(3) as PartialValue<TestMapData, TestMapDataPartial>|undefined : undefined;
        o.baseStructPtr = fieldMap?.has(4) ? fieldMap.get(4) as PartialValue<TestMapData|undefined, TestMapDataPartial>|undefined : undefined;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.mapPtrTest, TestStatePartial._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.baseField, TestStatePartial._fieldInfo[1], wi);
        ReStreamEncoders.serializeField(this.baseStruct, TestStatePartial._fieldInfo[2], wi);
        ReStreamEncoders.serializeField(this.baseStructPtr, TestStatePartial._fieldInfo[3], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "MapPtrTest", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPointer(false, new VarInfoStruct("PartialModMap", "restream", PartialModMap, undefined, [new VarInfoPrimitive(SerializationType.Uint8), new VarInfoPointer(false, new VarInfoStruct("TestMapData", "storetest", TestMapData)), new VarInfoPointer(false, new VarInfoStruct("TestMapDataPartial", "storetest", TestMapDataPartial))]))},
        {name: "BaseField", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.String))},
        {name: "BaseStruct", fieldIdx: 2, fieldID: 3, varInfo: new VarInfoPointer(false, new VarInfoStruct("PartialValue", "restream", PartialValue, undefined, [new VarInfoStruct("TestMapData", "storetest", TestMapData), new VarInfoPointer(false, new VarInfoStruct("TestMapDataPartial", "storetest", TestMapDataPartial))]))},
        {name: "BaseStructPtr", fieldIdx: 3, fieldID: 4, varInfo: new VarInfoPointer(false, new VarInfoStruct("PartialValue", "restream", PartialValue, undefined, [new VarInfoPointer(false, new VarInfoStruct("TestMapData", "storetest", TestMapData)), new VarInfoPointer(false, new VarInfoStruct("TestMapDataPartial", "storetest", TestMapDataPartial))]))},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
        [3, this._fieldInfo[2]],
        [4, this._fieldInfo[3]],
	]);

    applyTo(por: TestState): (string | number)[][] {
        const ret: (string | number)[][] = [];
        if (this.mapPtrTest !== undefined) { if (!(por.mapPtrTest instanceof Map)) { por.mapPtrTest = new Map(); } const fs = this.mapPtrTest.applyTo(por.mapPtrTest!); for (const f of fs) { ret.push(["mapPtrTest",...f]); }}
        if (this.baseField !== undefined) { por.baseField = this.baseField; ret.push(["baseField"]); }
        if (this.baseStruct !== undefined) { let fs; [por.baseStruct,fs] = this.baseStruct.applyOnTop(por.baseStruct); for (const f of fs) { ret.push(["baseStruct",...f]); }}
        if (this.baseStructPtr !== undefined) { let fs; [por.baseStructPtr,fs] = this.baseStructPtr.applyOnTop(por.baseStructPtr); for (const f of fs) { ret.push(["baseStructPtr",...f]); }}
        return ret;
    }
}

export class TestB {
    public a!: TestC;
    public b!: TestC;

    private constructor() {}

    public static fromValues(
        a: TestC = TestC.fromValues(),
        b: TestC = TestC.fromValues(),
    ) {
        const o = new TestB();
        o.a = a;
        o.b = b;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestB._fieldMap);
        }
        const o = new TestB();
        o.a = fieldMap?.has(1) ? fieldMap.get(1) as TestC : TestC.fromValues();
        o.b = fieldMap?.has(2) ? fieldMap.get(2) as TestC : TestC.fromValues();
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.a, TestB._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.b, TestB._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "A", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoStruct("TestC", "storetest", TestC)},
        {name: "B", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoStruct("TestC", "storetest", TestC)},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);
}

export class TestBPartial {
    public a!: PartialValue<TestC, TestCPartial>|undefined;
    public b!: PartialValue<TestC, TestCPartial>|undefined;

    private constructor() {}

    public static fromValues(
        a: PartialValue<TestC, TestCPartial>|undefined = undefined,
        b: PartialValue<TestC, TestCPartial>|undefined = undefined,
    ) {
        const o = new TestBPartial();
        o.a = a;
        o.b = b;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestBPartial._fieldMap);
        }
        const o = new TestBPartial();
        o.a = fieldMap?.has(1) ? fieldMap.get(1) as PartialValue<TestC, TestCPartial>|undefined : undefined;
        o.b = fieldMap?.has(2) ? fieldMap.get(2) as PartialValue<TestC, TestCPartial>|undefined : undefined;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.a, TestBPartial._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.b, TestBPartial._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "A", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPointer(false, new VarInfoStruct("PartialValue", "restream", PartialValue, undefined, [new VarInfoStruct("TestC", "storetest", TestC), new VarInfoPointer(false, new VarInfoStruct("TestCPartial", "storetest", TestCPartial))]))},
        {name: "B", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPointer(false, new VarInfoStruct("PartialValue", "restream", PartialValue, undefined, [new VarInfoStruct("TestC", "storetest", TestC), new VarInfoPointer(false, new VarInfoStruct("TestCPartial", "storetest", TestCPartial))]))},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);

    applyTo(por: TestB): (string | number)[][] {
        const ret: (string | number)[][] = [];
        if (this.a !== undefined) { let fs; [por.a,fs] = this.a.applyOnTop(por.a); for (const f of fs) { ret.push(["a",...f]); }}
        if (this.b !== undefined) { let fs; [por.b,fs] = this.b.applyOnTop(por.b); for (const f of fs) { ret.push(["b",...f]); }}
        return ret;
    }
}

export class TestA {
    public a!: TestB;
    public b!: TestB;

    private constructor() {}

    public static fromValues(
        a: TestB = TestB.fromValues(),
        b: TestB = TestB.fromValues(),
    ) {
        const o = new TestA();
        o.a = a;
        o.b = b;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestA._fieldMap);
        }
        const o = new TestA();
        o.a = fieldMap?.has(1) ? fieldMap.get(1) as TestB : TestB.fromValues();
        o.b = fieldMap?.has(2) ? fieldMap.get(2) as TestB : TestB.fromValues();
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.a, TestA._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.b, TestA._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "A", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoStruct("TestB", "storetest", TestB)},
        {name: "B", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoStruct("TestB", "storetest", TestB)},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);
}

export class TestAPartial {
    public a!: PartialValue<TestB, TestBPartial>|undefined;
    public b!: PartialValue<TestB, TestBPartial>|undefined;

    private constructor() {}

    public static fromValues(
        a: PartialValue<TestB, TestBPartial>|undefined = undefined,
        b: PartialValue<TestB, TestBPartial>|undefined = undefined,
    ) {
        const o = new TestAPartial();
        o.a = a;
        o.b = b;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), TestAPartial._fieldMap);
        }
        const o = new TestAPartial();
        o.a = fieldMap?.has(1) ? fieldMap.get(1) as PartialValue<TestB, TestBPartial>|undefined : undefined;
        o.b = fieldMap?.has(2) ? fieldMap.get(2) as PartialValue<TestB, TestBPartial>|undefined : undefined;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.a, TestAPartial._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.b, TestAPartial._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "A", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPointer(false, new VarInfoStruct("PartialValue", "restream", PartialValue, undefined, [new VarInfoStruct("TestB", "storetest", TestB), new VarInfoPointer(false, new VarInfoStruct("TestBPartial", "storetest", TestBPartial))]))},
        {name: "B", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPointer(false, new VarInfoStruct("PartialValue", "restream", PartialValue, undefined, [new VarInfoStruct("TestB", "storetest", TestB), new VarInfoPointer(false, new VarInfoStruct("TestBPartial", "storetest", TestBPartial))]))},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);

    applyTo(por: TestA): (string | number)[][] {
        const ret: (string | number)[][] = [];
        if (this.a !== undefined) { let fs; [por.a,fs] = this.a.applyOnTop(por.a); for (const f of fs) { ret.push(["a",...f]); }}
        if (this.b !== undefined) { let fs; [por.b,fs] = this.b.applyOnTop(por.b); for (const f of fs) { ret.push(["b",...f]); }}
        return ret;
    }
}
