// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
 
 
import BinaryReader from '../utils/BinaryReader.js';
import BinaryWriter from '../utils/BinaryWriter.js';
import * as ReStreamDecoders from '../utils/Decoders.js';
import * as ReStreamEncoders from '../utils/Encoders.js';
import { VarInfoPrimitive, VarInfoStruct, VarInfoGenericParam, VarInfoPointer, VarInfoArray, VarInfoMap, SerializationType } from '../utils/SerializationTypes.js';
import type { VarInfo, FieldInfo, AppliablePartial, AppliableOnTopPartial } from '../utils/SerializationTypes.js';

export type AccessLevel = number;

export const SocketEventNameStoreUpdate = "storeupdate";

export enum StoreSubscriptionAction {
    Subscribe = 0,
    Unsubscribe = 1,
}

export const StoreUpdateFull = 0;

export enum StoreUpdateMessageKind {
    StoreUpdateFull = 0,
    StoreUpdatePartial = 2,
}

export const Subscribe = 0;

export const compoundKeyJoinerString = "%&";

export class PartialArray<V> {
    public dataSets!: Map<number,V>;
    public whole!: V[]|undefined;

    private constructor() {}

    public static fromValues<V>(
        dataSets: Map<number,V> = new Map(),
        whole: V[]|undefined = [],
    ) {
        const o = new PartialArray<V>();
        o.dataSets = dataSets;
        o.whole = whole;
        return o;
    }

    public static deserialized<V>(r: BinaryReader, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["V", vi!.genericTypes![0]],
        ]);
        const o = new PartialArray<V>();
        o.dataSets = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo.fillGenerics(gm));
        o.whole = ReStreamDecoders.deserializeValue(r, this._fieldInfo[1].varInfo.fillGenerics(gm));
        return o;
    }

    public serialize(w: BinaryWriter, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["V", vi!.genericTypes![0]],
    ]);
        ReStreamEncoders.serializeValue(this.dataSets, w, PartialArray._fieldInfo[0].varInfo.fillGenerics(gm));
        ReStreamEncoders.serializeValue(this.whole, w, PartialArray._fieldInfo[1].varInfo.fillGenerics(gm));
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "dataSets", fieldIdx: 0, varInfo: new VarInfoMap(true, new VarInfoPrimitive(SerializationType.Int64, "int"), new VarInfoGenericParam("V"))},
        {name: "whole", fieldIdx: 1, varInfo: new VarInfoArray(false, new VarInfoGenericParam("V"))},
	];

    applyTo(por: V[]): (string | number)[][] {
        const ret: (string | number)[][] = [];
        if (this.whole) {
            por.splice(0, por.length, ...this.whole);
            ret.push([]);
        }
        for (const [k, v] of this.dataSets) {
            por[k] = v;
            if (!this.whole) {
                ret.push([k as string|number]);
            }
        }
        return ret;
    }
}

export class PartialMap<K extends string|number, V> {
    public dataSets!: Map<K,V>;
    public dataDeletes!: Set<K>;
    public whole!: Map<K,V>|undefined;

    private constructor() {}

    public static fromValues<K extends string|number, V>(
        dataSets: Map<K,V> = new Map(),
        dataDeletes: Set<K> = new Set(),
        whole: Map<K,V>|undefined = undefined,
    ) {
        const o = new PartialMap<K,V>();
        o.dataSets = dataSets;
        o.dataDeletes = dataDeletes;
        o.whole = whole;
        return o;
    }

    public static deserialized<K extends string|number, V>(r: BinaryReader, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["K", vi!.genericTypes![0]],
            ["V", vi!.genericTypes![1]],
        ]);
        const o = new PartialMap<K,V>();
        o.dataSets = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo.fillGenerics(gm));
        o.dataDeletes = ReStreamDecoders.deserializeValue(r, this._fieldInfo[1].varInfo.fillGenerics(gm));
        o.whole = ReStreamDecoders.deserializeValue(r, this._fieldInfo[2].varInfo.fillGenerics(gm));
        return o;
    }

    public serialize(w: BinaryWriter, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["K", vi!.genericTypes![0]],
            ["V", vi!.genericTypes![1]],
    ]);
        ReStreamEncoders.serializeValue(this.dataSets, w, PartialMap._fieldInfo[0].varInfo.fillGenerics(gm));
        ReStreamEncoders.serializeValue(this.dataDeletes, w, PartialMap._fieldInfo[1].varInfo.fillGenerics(gm));
        ReStreamEncoders.serializeValue(this.whole, w, PartialMap._fieldInfo[2].varInfo.fillGenerics(gm));
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "dataSets", fieldIdx: 0, varInfo: new VarInfoMap(true, new VarInfoGenericParam("K"), new VarInfoGenericParam("V"))},
        {name: "dataDeletes", fieldIdx: 1, varInfo: new VarInfoMap(true, new VarInfoGenericParam("K"), undefined)},
        {name: "whole", fieldIdx: 2, varInfo: new VarInfoMap(false, new VarInfoGenericParam("K"), new VarInfoGenericParam("V"))},
	];

	applyTo(por: Map<K, V>): (string | number)[][] {
		const ret: (string | number)[][] = [];
		if (this.whole) {
			por.clear();
			for (const [k, v] of this.whole) {
				por.set(k, v);
			}
			ret.push([]);
		}
		for (const [k, v] of this.dataSets) {
			por.set(k, v);
			if (!this.whole) {
				ret.push([k as string|number]);
			}
		}
		for (const k of this.dataDeletes) {
			por.delete(k);
			if (!this.whole) {
				ret.push([k as string|number]);
			}
		}
		return ret;
	}
}

export class PartialModArray<V, P extends AppliablePartial<V>|AppliableOnTopPartial<V>> {
    public dataSets!: Map<number,V>;
    public dataMods!: Map<number,P>;
    public whole!: V[]|undefined;

    private constructor() {}

    public static fromValues<V, P extends AppliablePartial<V>|AppliableOnTopPartial<V>>(
        dataSets: Map<number,V> = new Map(),
        dataMods: Map<number,P> = new Map(),
        whole: V[]|undefined = [],
    ) {
        const o = new PartialModArray<V,P>();
        o.dataSets = dataSets;
        o.dataMods = dataMods;
        o.whole = whole;
        return o;
    }

    public static deserialized<V, P extends AppliablePartial<V>|AppliableOnTopPartial<V>>(r: BinaryReader, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["V", vi!.genericTypes![0]],
            ["P", vi!.genericTypes![1]],
        ]);
        const o = new PartialModArray<V,P>();
        o.dataSets = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo.fillGenerics(gm));
        o.dataMods = ReStreamDecoders.deserializeValue(r, this._fieldInfo[1].varInfo.fillGenerics(gm));
        o.whole = ReStreamDecoders.deserializeValue(r, this._fieldInfo[2].varInfo.fillGenerics(gm));
        return o;
    }

    public serialize(w: BinaryWriter, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["V", vi!.genericTypes![0]],
            ["P", vi!.genericTypes![1]],
    ]);
        ReStreamEncoders.serializeValue(this.dataSets, w, PartialModArray._fieldInfo[0].varInfo.fillGenerics(gm));
        ReStreamEncoders.serializeValue(this.dataMods, w, PartialModArray._fieldInfo[1].varInfo.fillGenerics(gm));
        ReStreamEncoders.serializeValue(this.whole, w, PartialModArray._fieldInfo[2].varInfo.fillGenerics(gm));
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "dataSets", fieldIdx: 0, varInfo: new VarInfoMap(true, new VarInfoPrimitive(SerializationType.Int64, "int"), new VarInfoGenericParam("V"))},
        {name: "dataMods", fieldIdx: 1, varInfo: new VarInfoMap(true, new VarInfoPrimitive(SerializationType.Int64, "int"), new VarInfoGenericParam("P"))},
        {name: "whole", fieldIdx: 2, varInfo: new VarInfoArray(false, new VarInfoGenericParam("V"))},
	];

    applyTo(por: V[]): (string | number)[][] {
        const ret: (string | number)[][] = [];
        if (this.whole) {
            por.splice(0, por.length, ...this.whole);
            ret.push([]);
        }
        for (const [k, v] of this.dataSets) {
            por[k] = v;
            if (!this.whole) {
                ret.push([k as string|number]);
            }
        }
        for (const [k, pv] of this.dataMods) {
            let fs: (string | number)[][] = [];
            if ((pv as AppliablePartial<V>).applyTo) {
                fs = (pv as AppliablePartial<V>).applyTo(por[k]!)
            }
            if ((pv as AppliableOnTopPartial<V>).applyOnTop) {
                let nv: V;
                [nv, fs] = (pv as AppliableOnTopPartial<V>).applyOnTop(por[k])
                por[k] = nv;
            }

            if (!this.whole) {
                for (const fss of fs) {
                    ret.push([k as string|number, ...fss]);
                }
            }
        }
        return ret;
    }
}

export class PartialModMap<K extends string|number, V, P extends AppliablePartial<V>|AppliableOnTopPartial<V>> {
    public dataSets!: Map<K,V>;
    public dataDeletes!: Set<K>;
    public dataMods!: Map<K,P>;
    public whole!: Map<K,V>|undefined;

    private constructor() {}

    public static fromValues<K extends string|number, V, P extends AppliablePartial<V>|AppliableOnTopPartial<V>>(
        dataSets: Map<K,V> = new Map(),
        dataDeletes: Set<K> = new Set(),
        dataMods: Map<K,P> = new Map(),
        whole: Map<K,V>|undefined = undefined,
    ) {
        const o = new PartialModMap<K,V,P>();
        o.dataSets = dataSets;
        o.dataDeletes = dataDeletes;
        o.dataMods = dataMods;
        o.whole = whole;
        return o;
    }

    public static deserialized<K extends string|number, V, P extends AppliablePartial<V>|AppliableOnTopPartial<V>>(r: BinaryReader, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["K", vi!.genericTypes![0]],
            ["V", vi!.genericTypes![1]],
            ["P", vi!.genericTypes![2]],
        ]);
        const o = new PartialModMap<K,V,P>();
        o.dataSets = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo.fillGenerics(gm));
        o.dataDeletes = ReStreamDecoders.deserializeValue(r, this._fieldInfo[1].varInfo.fillGenerics(gm));
        o.dataMods = ReStreamDecoders.deserializeValue(r, this._fieldInfo[2].varInfo.fillGenerics(gm));
        o.whole = ReStreamDecoders.deserializeValue(r, this._fieldInfo[3].varInfo.fillGenerics(gm));
        return o;
    }

    public serialize(w: BinaryWriter, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["K", vi!.genericTypes![0]],
            ["V", vi!.genericTypes![1]],
            ["P", vi!.genericTypes![2]],
    ]);
        ReStreamEncoders.serializeValue(this.dataSets, w, PartialModMap._fieldInfo[0].varInfo.fillGenerics(gm));
        ReStreamEncoders.serializeValue(this.dataDeletes, w, PartialModMap._fieldInfo[1].varInfo.fillGenerics(gm));
        ReStreamEncoders.serializeValue(this.dataMods, w, PartialModMap._fieldInfo[2].varInfo.fillGenerics(gm));
        ReStreamEncoders.serializeValue(this.whole, w, PartialModMap._fieldInfo[3].varInfo.fillGenerics(gm));
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "dataSets", fieldIdx: 0, varInfo: new VarInfoMap(true, new VarInfoGenericParam("K"), new VarInfoGenericParam("V"))},
        {name: "dataDeletes", fieldIdx: 1, varInfo: new VarInfoMap(true, new VarInfoGenericParam("K"), undefined)},
        {name: "dataMods", fieldIdx: 2, varInfo: new VarInfoMap(true, new VarInfoGenericParam("K"), new VarInfoGenericParam("P"))},
        {name: "whole", fieldIdx: 3, varInfo: new VarInfoMap(false, new VarInfoGenericParam("K"), new VarInfoGenericParam("V"))},
	];

	applyTo(por: Map<K, V>): (string | number)[][] {
		const ret: (string | number)[][] = [];
		if (this.whole) {
			por.clear();
			for (const [k, v] of this.whole) {
				por.set(k, v);
			}
			ret.push([]);
		}
		for (const [k, v] of this.dataSets) {
			por.set(k, v);
			if (!this.whole) {
				ret.push([k as string|number]);
			}
		}
		for (const k of this.dataDeletes) {
			por.delete(k);
			if (!this.whole) {
				ret.push([k as string|number]);
			}
		}
		for (const [k, pv] of this.dataMods) {
			let fs: (string | number)[][] = [];
			if ((pv as AppliablePartial<V>).applyTo) {
				fs = (pv as AppliablePartial<V>).applyTo(por.get(k)!)
			}
			if ((pv as AppliableOnTopPartial<V>).applyOnTop) {
				let nv: V;
				[nv, fs] = (pv as AppliableOnTopPartial<V>).applyOnTop(por.get(k)!)
				por.set(k, nv);
			}
			if (!this.whole) {
				for (const fss of fs) {
					ret.push([k as string|number, ...fss]);
				}
			}
		}
		return ret;
	}
}

export class PartialValue<V, P extends AppliablePartial<V>|AppliableOnTopPartial<V>> {
    public whole!: V|undefined;
    public partial!: P|undefined;

    private constructor() {}

    public static fromValues<V, P extends AppliablePartial<V>|AppliableOnTopPartial<V>>(
        whole: V|undefined = undefined,
        partial: P|undefined = undefined,
    ) {
        const o = new PartialValue<V,P>();
        o.whole = whole;
        o.partial = partial;
        return o;
    }

    public static deserialized<V, P extends AppliablePartial<V>|AppliableOnTopPartial<V>>(r: BinaryReader, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["V", vi!.genericTypes![0]],
            ["P", vi!.genericTypes![1]],
        ]);
        const o = new PartialValue<V,P>();
        o.whole = ReStreamDecoders.deserializeValue(r, this._fieldInfo[0].varInfo.fillGenerics(gm));
        o.partial = ReStreamDecoders.deserializeValue(r, this._fieldInfo[1].varInfo.fillGenerics(gm));
        return o;
    }

    public serialize(w: BinaryWriter, vi: VarInfoStruct | undefined) {
    	const gm = new Map<string,VarInfo>([
            ["V", vi!.genericTypes![0]],
            ["P", vi!.genericTypes![1]],
    ]);
        ReStreamEncoders.serializeValue(this.whole, w, PartialValue._fieldInfo[0].varInfo.fillGenerics(gm));
        ReStreamEncoders.serializeValue(this.partial, w, PartialValue._fieldInfo[1].varInfo.fillGenerics(gm));
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "whole", fieldIdx: 0, varInfo: new VarInfoPointer(false, new VarInfoGenericParam("V"))},
        {name: "partial", fieldIdx: 1, varInfo: new VarInfoPointer(false, new VarInfoGenericParam("P"))},
	];

    applyOnTop(por: V): [V, (string | number)[][]] {
        const ret: [V, (string | number)[][]] = [por, []];
        if (this.whole) {
            ret[0] = this.whole;
            ret[1].push([]);
        }
        if (this.partial) {
            let fs: (string | number)[][] = [];
            if ((this.partial as AppliablePartial<V>).applyTo) {
                fs = (this.partial as AppliablePartial<V>).applyTo(ret[0]);
            }
            if ((this.partial as AppliableOnTopPartial<V>).applyOnTop) {
                [ret[0], fs] = (this.partial as AppliableOnTopPartial<V>).applyOnTop(ret[0]);
            }

            if (!this.whole) {
                ret[1] = fs;
            }
        }
        return ret;
    }
}
