// FILE IS GENERATED BY THE restream PACKAGE, DO NOT MODIFY DIRECTLY!
 
/* eslint-disable @typescript-eslint/no-unused-vars */
import * as ReStreamDecoders from '@boatkit-io/restream';
import * as ReStreamEncoders from '@boatkit-io/restream';
import { BinaryReader, BinaryWriter, SerializationType, VarInfoArray, VarInfoPointer, VarInfoPrimitive, VarInfoStruct } from '@boatkit-io/restream';
import type { FieldInfo } from '@boatkit-io/restream';
import { PartialArray } from '@boatkit-io/restream';

export const BoardStoreName = "BoardStore";

export class BoardStoreState {
    public board!: (string[]|undefined)[]|undefined;
    public xTurn!: boolean;

    private constructor() {}

    public static fromValues(
        board: (string[]|undefined)[]|undefined = [],
        xTurn: boolean = false,
    ) {
        const o = new BoardStoreState();
        o.board = board;
        o.xTurn = xTurn;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), BoardStoreState._fieldMap);
        }
        const o = new BoardStoreState();
        o.board = fieldMap?.has(1) ? fieldMap.get(1) as (string[]|undefined)[]|undefined : [];
        o.xTurn = fieldMap?.has(2) ? fieldMap.get(2) as boolean : false;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.board, BoardStoreState._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.xTurn, BoardStoreState._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Board", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoArray(false, new VarInfoArray(false, new VarInfoPrimitive(SerializationType.String)))},
        {name: "XTurn", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPrimitive(SerializationType.Bool)},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);
}

export class BoardStoreStatePartial {
    public board!: PartialArray<string[]|undefined>|undefined;
    public xTurn!: boolean|undefined;

    private constructor() {}

    public static fromValues(
        board: PartialArray<string[]|undefined>|undefined = undefined,
        xTurn: boolean|undefined = undefined,
    ) {
        const o = new BoardStoreStatePartial();
        o.board = board;
        o.xTurn = xTurn;
        return o;
    }

    public static deserialized(r: BinaryReader) {
        let fieldMap: Map<number, unknown>|undefined;
        if (r) {
            const sl = ReStreamDecoders.decodeUint32(r);
            fieldMap = ReStreamDecoders.decodeFieldMap(r.slice(sl), BoardStoreStatePartial._fieldMap);
        }
        const o = new BoardStoreStatePartial();
        o.board = fieldMap?.has(1) ? fieldMap.get(1) as PartialArray<string[]|undefined>|undefined : undefined;
        o.xTurn = fieldMap?.has(2) ? fieldMap.get(2) as boolean|undefined : undefined;
        return o;
    }

    public serialize(w: BinaryWriter, _: VarInfoStruct | undefined) {
        const wi = new BinaryWriter();
        ReStreamEncoders.serializeField(this.board, BoardStoreStatePartial._fieldInfo[0], wi);
        ReStreamEncoders.serializeField(this.xTurn, BoardStoreStatePartial._fieldInfo[1], wi);
        const b = wi.getBytes();
        ReStreamEncoders.serializePackedInt(b.length, w);
        w.writeBytes(b);
    }

	private static _fieldInfo: FieldInfo[] = [
        {name: "Board", fieldIdx: 0, fieldID: 1, varInfo: new VarInfoPointer(false, new VarInfoStruct("PartialArray", "restream", PartialArray, undefined, [new VarInfoArray(false, new VarInfoPrimitive(SerializationType.String))]))},
        {name: "XTurn", fieldIdx: 1, fieldID: 2, varInfo: new VarInfoPointer(false, new VarInfoPrimitive(SerializationType.Bool))},
	];

	private static _fieldMap = new Map<number,FieldInfo>([
        [1, this._fieldInfo[0]],
        [2, this._fieldInfo[1]],
	]);

    applyTo(por: BoardStoreState): (string | number)[][] {
        const ret: (string | number)[][] = [];
        if (this.board !== undefined) { if (!Array.isArray(por.board)) { por.board = Array.from(por.board ?? []); } const fs = this.board.applyTo(por.board!); for (const f of fs) { ret.push(["board",...f]); }}
        if (this.xTurn !== undefined) { por.xTurn = this.xTurn; ret.push(["xTurn"]); }
        return ret;
    }
}
